// src/cache-calculator/pricing.ts
// ⚠️ AUTO-GENERATED by scripts/codegen-pricing.cjs — DO NOT EDIT MANUALLY.
// Source of truth: src/data/pricing.json. Run `node scripts/codegen-pricing.cjs --write` to regenerate.
//
// Per-vendor pricing data for prompt caching cost calculator.
// Each vendor has fundamentally different caching semantics — do not fold into a single formula.

export const LAST_UPDATED = '2026-06-25'

export type ModelId =
  | 'claude-opus-4-8'
  | 'claude-sonnet-4-6'
  | 'claude-haiku-4-5'
  | 'gpt-5-5'
  | 'gpt-5-4'
  | 'gpt-5-4-mini'
  | 'deepseek-v4-pro'
  | 'deepseek-v4-flash'
  | 'gemini-3-5-flash'
  | 'gemini-2-5-flash'
  | 'gemini-2-5-flash-lite'
  | 'claude-fable-5'
  | 'gemini-2-5-pro'
  | 'gemini-3-1-pro'
  | 'grok-4-20'
  | 'glm-5-2'
  | 'kimi-k2-7'

export interface ModelPricing {
  id: ModelId
  vendor: 'anthropic' | 'openai' | 'deepseek' | 'google' | 'xai' | 'zhipu' | 'moonshot'
  label: string
  inputPerMillion: number   // USD per 1M input tokens (no cache)
  outputPerMillion: number  // USD per 1M output tokens
  cacheWriteMultiplier: number   // input * this = cache write cost
  cacheReadMultiplier: number    // input * this = cache read cost
  cacheNotes: string             // shown to user under model select
  cacheTtlDescription: string
  sourceUrl: string
}

// Anthropic Claude — explicit cache_control breakpoint, 5min default / 1hr opt-in
// OpenAI — automatic prompt caching for prompts >=1024 tokens, LRU eviction
// DeepSeek V4 — automatic context cache, prefix-based
// Google Gemini — explicit context caching API, storage charged separately

export const MODELS: ModelPricing[] = [
  {
    id: 'claude-opus-4-8',
    vendor: 'anthropic',
    label: 'Claude Opus 4.8',
    inputPerMillion: 5,
    outputPerMillion: 25,
    cacheWriteMultiplier: 1.25,
    cacheReadMultiplier: 0.1,
    cacheNotes: 'Explicit cache_control. Min 1024 tokens. 5-min TTL by default.',
    cacheTtlDescription: '5 min default / 1 hr opt-in',
    sourceUrl: 'https://platform.claude.com/docs/en/about-claude/pricing',
  },

  {
    id: 'claude-sonnet-4-6',
    vendor: 'anthropic',
    label: 'Claude Sonnet 4.6',
    inputPerMillion: 3,
    outputPerMillion: 15,
    cacheWriteMultiplier: 1.25,
    cacheReadMultiplier: 0.1,
    cacheNotes: 'Explicit cache_control. Min 1024 tokens. 5-min TTL by default.',
    cacheTtlDescription: '5 min default / 1 hr opt-in',
    sourceUrl: 'https://platform.claude.com/docs/en/about-claude/pricing',
  },

  {
    id: 'claude-haiku-4-5',
    vendor: 'anthropic',
    label: 'Claude Haiku 4.5',
    inputPerMillion: 1,
    outputPerMillion: 5,
    cacheWriteMultiplier: 1.25,
    cacheReadMultiplier: 0.1,
    cacheNotes: 'Explicit cache_control. Min 2048 tokens (Haiku).',
    cacheTtlDescription: '5 min default / 1 hr opt-in',
    sourceUrl: 'https://platform.claude.com/docs/en/about-claude/pricing',
  },

  {
    id: 'gpt-5-5',
    vendor: 'openai',
    label: 'GPT-5.5',
    inputPerMillion: 5,
    outputPerMillion: 30,
    cacheWriteMultiplier: 1,
    cacheReadMultiplier: 0.1,
    cacheNotes: 'Automatic for prompts >= 1024 tokens. No write cost. Cache eviction is LRU.',
    cacheTtlDescription: 'Auto, minutes-hours (LRU)',
    sourceUrl: 'https://openai.com/api/pricing/',
  },

  {
    id: 'gpt-5-4',
    vendor: 'openai',
    label: 'GPT-5.4',
    inputPerMillion: 2.5,
    outputPerMillion: 15,
    cacheWriteMultiplier: 1,
    cacheReadMultiplier: 0.1,
    cacheNotes: 'Automatic for prompts >= 1024 tokens. No write cost. Cache eviction is LRU.',
    cacheTtlDescription: 'Auto, minutes-hours (LRU)',
    sourceUrl: 'https://openai.com/api/pricing/',
  },

  {
    id: 'gpt-5-4-mini',
    vendor: 'openai',
    label: 'GPT-5.4 mini',
    inputPerMillion: 0.75,
    outputPerMillion: 4.5,
    cacheWriteMultiplier: 1,
    cacheReadMultiplier: 0.1,
    cacheNotes: 'Automatic for prompts >= 1024 tokens. No write cost.',
    cacheTtlDescription: 'Auto, minutes-hours (LRU)',
    sourceUrl: 'https://openai.com/api/pricing/',
  },

  {
    id: 'deepseek-v4-pro',
    vendor: 'deepseek',
    label: 'DeepSeek V4 Pro',
    inputPerMillion: 0.435,
    outputPerMillion: 0.87,
    cacheWriteMultiplier: 1,
    cacheReadMultiplier: 0.00833,
    cacheNotes: 'Automatic prefix cache. Cache hit ≈ 0.83% of input price.',
    cacheTtlDescription: 'Auto (prefix-based)',
    sourceUrl: 'https://api-docs.deepseek.com/quick_start/pricing',
  },

  {
    id: 'deepseek-v4-flash',
    vendor: 'deepseek',
    label: 'DeepSeek V4 Flash',
    inputPerMillion: 0.14,
    outputPerMillion: 0.28,
    cacheWriteMultiplier: 1,
    cacheReadMultiplier: 0.02,
    cacheNotes: 'Automatic prefix cache. Cache hit = 2% of input price.',
    cacheTtlDescription: 'Auto (prefix-based)',
    sourceUrl: 'https://api-docs.deepseek.com/quick_start/pricing',
  },

  {
    id: 'gemini-3-5-flash',
    vendor: 'google',
    label: 'Gemini 3.5 Flash',
    inputPerMillion: 1.5,
    outputPerMillion: 9,
    cacheWriteMultiplier: 1,
    cacheReadMultiplier: 0.1,
    cacheNotes: 'Explicit context cache. Storage charged separately ($1/M/hr, not included).',
    cacheTtlDescription: 'Configurable (default 1 hr)',
    sourceUrl: 'https://ai.google.dev/gemini-api/docs/pricing',
  },

  {
    id: 'gemini-2-5-flash',
    vendor: 'google',
    label: 'Gemini 2.5 Flash',
    inputPerMillion: 0.3,
    outputPerMillion: 2.5,
    cacheWriteMultiplier: 1,
    cacheReadMultiplier: 0.1,
    cacheNotes: 'Explicit context cache. Storage charged separately ($1/M/hr, not included).',
    cacheTtlDescription: 'Configurable (default 1 hr)',
    sourceUrl: 'https://ai.google.dev/gemini-api/docs/pricing',
  },

  {
    id: 'gemini-2-5-flash-lite',
    vendor: 'google',
    label: 'Gemini 2.5 Flash-Lite',
    inputPerMillion: 0.1,
    outputPerMillion: 0.4,
    cacheWriteMultiplier: 1,
    cacheReadMultiplier: 0.1,
    cacheNotes: 'Explicit context cache. Storage charged separately ($1/M/hr, not included).',
    cacheTtlDescription: 'Configurable (default 1 hr)',
    sourceUrl: 'https://ai.google.dev/gemini-api/docs/pricing',
  },

  {
    id: 'claude-fable-5',
    vendor: 'anthropic',
    label: 'Claude Fable 5',
    inputPerMillion: 10,
    outputPerMillion: 50,
    cacheWriteMultiplier: 1.25,
    cacheReadMultiplier: 0.1,
    cacheNotes: 'Explicit cache_control. Min 1024 tokens. 5-min TTL by default.',
    cacheTtlDescription: '5 min default / 1 hr opt-in',
    sourceUrl: 'https://platform.claude.com/docs/en/about-claude/pricing',
  },

  {
    id: 'gemini-2-5-pro',
    vendor: 'google',
    label: 'Gemini 2.5 Pro',
    inputPerMillion: 1.25,
    outputPerMillion: 10,
    cacheWriteMultiplier: 1,
    cacheReadMultiplier: 0.1,
    cacheNotes: 'Explicit context cache. Storage charged separately ($1/M/hr, not included).',
    cacheTtlDescription: 'Configurable (default 1 hr)',
    sourceUrl: 'https://ai.google.dev/gemini-api/docs/pricing',
  },

  {
    id: 'gemini-3-1-pro',
    vendor: 'google',
    label: 'Gemini 3.1 Pro',
    inputPerMillion: 2,
    outputPerMillion: 12,
    cacheWriteMultiplier: 1,
    cacheReadMultiplier: 0.1,
    cacheNotes: 'Explicit context cache. Storage charged separately ($1/M/hr, not included).',
    cacheTtlDescription: 'Configurable (default 1 hr)',
    sourceUrl: 'https://ai.google.dev/gemini-api/docs/pricing',
  },

  {
    id: 'grok-4-20',
    vendor: 'xai',
    label: 'Grok 4.20',
    inputPerMillion: 1.25,
    outputPerMillion: 2.5,
    cacheWriteMultiplier: 1,
    cacheReadMultiplier: 0.16,
    cacheNotes: 'Automatic prompt caching. Set x-grok-conv-id header to maximize hit rate.',
    cacheTtlDescription: 'Auto (minutes-hours, LRU)',
    sourceUrl: 'https://docs.x.ai/docs/models',
  },

  {
    id: 'glm-5-2',
    vendor: 'zhipu',
    label: 'GLM-5.2',
    inputPerMillion: 0.95,
    outputPerMillion: 3,
    cacheWriteMultiplier: 1,
    cacheReadMultiplier: 0.17,
    cacheNotes: 'Implicit (automatic) context cache. No manual config needed.',
    cacheTtlDescription: 'Auto',
    sourceUrl: 'https://open.bigmodel.cn/pricing',
  },

  {
    id: 'kimi-k2-7',
    vendor: 'moonshot',
    label: 'Kimi K2.7',
    inputPerMillion: 0.74,
    outputPerMillion: 3.5,
    cacheWriteMultiplier: 1,
    cacheReadMultiplier: 0.2,
    cacheNotes: 'Context caching for repeated long context. Write at input price, reads discounted.',
    cacheTtlDescription: 'Auto / configurable',
    sourceUrl: 'https://platform.moonshot.cn/docs/pricing',
  },
]
