export interface LongTailPage {
  slug: string
  cron: string
  title: string
  h1: string
  description: string
  explanation: string
  faq: { q: string; a: string }[]
  keywords: string[]
}

export const LONG_TAIL_PAGES: LongTailPage[] = [
  // === Every N minutes ===
  { slug: 'every-minute', cron: '* * * * *', title: 'Cron Every Minute - Run a Job Every 60 Seconds', h1: 'Cron Every Minute', description: 'How to run a cron job every minute. Use * * * * * to execute a command every 60 seconds. Examples for Unix, Quartz, and AWS.', explanation: 'The cron expression * * * * * runs a command every single minute. All fields are wildcards (*), meaning there is no restriction on any time component.', faq: [{ q: 'What cron expression runs every minute?', a: 'Use * * * * * in Unix cron. For Quartz, use 0 * * ? * *. For AWS EventBridge, use cron(* * ? * * *).' }, { q: 'Is running a job every minute safe?', a: 'It depends on the job. Make sure each execution completes within 60 seconds to avoid overlapping runs. Consider using a lock file or queue system for critical tasks.' }], keywords: ['cron every minute', 'every 1 minute cron', 'crontab every minute', '* * * * *'] },
  { slug: 'every-5-minutes', cron: '*/5 * * * *', title: 'Cron Every 5 Minutes - Schedule & Examples', h1: 'Cron Every 5 Minutes', description: 'Schedule a cron job every 5 minutes with */5 * * * *. Learn the syntax, see examples for Unix, Quartz, AWS, and get next run times.', explanation: 'The expression */5 * * * * uses the step operator (*/5) in the minute field. It triggers at minute 0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, and 55 every hour.', faq: [{ q: 'How do I set a cron job to run every 5 minutes?', a: 'Add this line to your crontab: */5 * * * * /path/to/command. The */5 means every 5th minute.' }, { q: 'What does */5 mean in cron?', a: '*/5 in the minute field means "every 5 units". The cron daemon checks if the current minute is divisible by 5 (0, 5, 10, 15, etc.).' }], keywords: ['cron every 5 minutes', '*/5 * * * *', 'crontab every 5 min'] },
  { slug: 'every-10-minutes', cron: '*/10 * * * *', title: 'Cron Every 10 Minutes - Expression & Examples', h1: 'Cron Every 10 Minutes', description: 'Run a cron job every 10 minutes with */10 * * * *. Complete guide with examples for all platforms.', explanation: 'The expression */10 * * * * triggers at minute 0, 10, 20, 30, 40, and 50 of every hour, every day.', faq: [{ q: 'What is the cron expression for every 10 minutes?', a: 'Use */10 * * * * in your crontab. This runs the command at minutes 0, 10, 20, 30, 40, and 50 each hour.' }], keywords: ['cron every 10 minutes', '*/10 * * * *', 'crontab every 10 min'] },
  { slug: 'every-15-minutes', cron: '*/15 * * * *', title: 'Cron Every 15 Minutes - Schedule & Syntax', h1: 'Cron Every 15 Minutes', description: 'Set up a cron job every 15 minutes with */15 * * * *. Works with Unix, Quartz, and AWS EventBridge.', explanation: 'The expression */15 * * * * runs at minute 0, 15, 30, and 45 of every hour.', faq: [{ q: 'How do I run a cron job every 15 minutes?', a: 'Use */15 * * * * in your crontab. This executes at minutes 0, 15, 30, and 45 each hour.' }], keywords: ['cron every 15 minutes', '*/15 * * * *'] },
  { slug: 'every-20-minutes', cron: '*/20 * * * *', title: 'Cron Every 20 Minutes - Expression Guide', h1: 'Cron Every 20 Minutes', description: 'Run a job every 20 minutes using */20 * * * *. Learn the syntax and see platform-specific examples.', explanation: 'The expression */20 * * * * triggers at minute 0, 20, and 40 of every hour.', faq: [{ q: 'What cron expression runs every 20 minutes?', a: 'Use */20 * * * * in your crontab file.' }], keywords: ['cron every 20 minutes', '*/20 * * * *'] },
  { slug: 'every-30-minutes', cron: '*/30 * * * *', title: 'Cron Every 30 Minutes - Half Hour Schedule', h1: 'Cron Every 30 Minutes', description: 'Schedule a cron job every 30 minutes (half hour) with */30 * * * *. Complete guide with examples.', explanation: 'The expression */30 * * * * runs at the top and bottom of every hour (minute 0 and minute 30).', faq: [{ q: 'How do I run a cron job every 30 minutes?', a: 'Use */30 * * * * in your crontab. This runs at minute 0 and minute 30 of each hour.' }, { q: 'Can I run a cron every half hour starting at :15?', a: 'Yes. Use 15,45 * * * * to run at :15 and :45 every hour.' }], keywords: ['cron every 30 minutes', '*/30 * * * *', 'cron half hour'] },
  { slug: 'every-45-minutes', cron: '*/45 * * * *', title: 'Cron Every 45 Minutes - Setup Guide', h1: 'Cron Every 45 Minutes', description: 'Run a cron job every 45 minutes. See the expression and examples.', explanation: 'The expression */45 * * * * triggers at minute 0 and minute 45 of every hour.', faq: [{ q: 'What is the cron for every 45 minutes?', a: 'Use */45 * * * *. It runs at minute 0 and 45 of each hour.' }], keywords: ['cron every 45 minutes', '*/45 * * * *'] },

  // === Every N hours ===
  { slug: 'every-hour', cron: '0 * * * *', title: 'Cron Every Hour - Hourly Job Schedule', h1: 'Cron Every Hour', description: 'Run a cron job every hour at minute 0 with 0 * * * *. See examples for hourly, bi-hourly, and custom schedules.', explanation: 'The expression 0 * * * * runs at the top of every hour (00:00, 01:00, 02:00, etc.) every day.', faq: [{ q: 'How do I run a cron job every hour?', a: 'Use 0 * * * * in your crontab. This runs at the start of every hour (minute 0).' }, { q: 'Can I run a cron job every hour at minute 30?', a: 'Yes. Use 30 * * * * to run at :30 past every hour.' }], keywords: ['cron every hour', 'hourly cron', '0 * * * *'] },
  { slug: 'every-2-hours', cron: '0 */2 * * *', title: 'Cron Every 2 Hours - Bi-Hourly Schedule', h1: 'Cron Every 2 Hours', description: 'Schedule a cron job every 2 hours with 0 */2 * * *. Runs at 00:00, 02:00, 04:00, etc.', explanation: 'The expression 0 */2 * * * runs at the top of every 2nd hour: 00:00, 02:00, 04:00, 06:00, etc.', faq: [{ q: 'What cron expression runs every 2 hours?', a: 'Use 0 */2 * * * in your crontab. This triggers at 00:00, 02:00, 04:00, and so on.' }], keywords: ['cron every 2 hours', '0 */2 * * *'] },
  { slug: 'every-3-hours', cron: '0 */3 * * *', title: 'Cron Every 3 Hours - Expression & Examples', h1: 'Cron Every 3 Hours', description: 'Run a cron job every 3 hours using 0 */3 * * *. Triggers at 00:00, 03:00, 06:00, etc.', explanation: 'The expression 0 */3 * * * runs at the top of every 3rd hour.', faq: [{ q: 'How do I run a cron job every 3 hours?', a: 'Use 0 */3 * * * in your crontab.' }], keywords: ['cron every 3 hours', '0 */3 * * *'] },
  { slug: 'every-4-hours', cron: '0 */4 * * *', title: 'Cron Every 4 Hours - Setup Guide', h1: 'Cron Every 4 Hours', description: 'Run a cron job every 4 hours with 0 */4 * * *. Fires at 00:00, 04:00, 08:00, 12:00, 16:00, 20:00.', explanation: 'The expression 0 */4 * * * runs 6 times per day: at 00:00, 04:00, 08:00, 12:00, 16:00, and 20:00.', faq: [{ q: 'What cron runs every 4 hours?', a: 'Use 0 */4 * * * in your crontab file.' }], keywords: ['cron every 4 hours', '0 */4 * * *'] },
  { slug: 'every-6-hours', cron: '0 */6 * * *', title: 'Cron Every 6 Hours - Quarter Day Schedule', h1: 'Cron Every 6 Hours', description: 'Run a cron job every 6 hours with 0 */6 * * *. Executes 4 times daily at 00:00, 06:00, 12:00, 18:00.', explanation: 'The expression 0 */6 * * * runs 4 times per day: midnight, 6 AM, noon, and 6 PM.', faq: [{ q: 'How do I schedule a cron every 6 hours?', a: 'Use 0 */6 * * * in your crontab. This runs at 00:00, 06:00, 12:00, and 18:00 daily.' }], keywords: ['cron every 6 hours', '0 */6 * * *'] },
  { slug: 'every-8-hours', cron: '0 */8 * * *', title: 'Cron Every 8 Hours - Expression Guide', h1: 'Cron Every 8 Hours', description: 'Schedule a cron job every 8 hours using 0 */8 * * *. Runs at 00:00, 08:00, and 16:00.', explanation: 'The expression 0 */8 * * * runs 3 times per day: at midnight, 8 AM, and 4 PM.', faq: [{ q: 'What cron runs every 8 hours?', a: 'Use 0 */8 * * * in your crontab.' }], keywords: ['cron every 8 hours', '0 */8 * * *'] },
  { slug: 'every-12-hours', cron: '0 */12 * * *', title: 'Cron Every 12 Hours - Twice Daily Schedule', h1: 'Cron Every 12 Hours', description: 'Run a cron job every 12 hours (twice daily) with 0 */12 * * *. Fires at midnight and noon.', explanation: 'The expression 0 */12 * * * runs twice per day: at midnight (00:00) and noon (12:00).', faq: [{ q: 'How do I run a cron twice a day?', a: 'Use 0 */12 * * * to run at 00:00 and 12:00. Or use 0 0,12 * * * for the same effect.' }], keywords: ['cron every 12 hours', 'twice daily cron', '0 */12 * * *'] },

  // === Daily schedules ===
  { slug: 'every-day-midnight', cron: '0 0 * * *', title: 'Cron Every Day at Midnight - Daily Schedule', h1: 'Cron Every Day at Midnight', description: 'Run a cron job every day at midnight (00:00) with 0 0 * * *. Daily schedule examples for all platforms.', explanation: 'The expression 0 0 * * * runs at 00:00 (midnight) every single day. Minute=0, Hour=0, and the remaining fields are wildcards.', faq: [{ q: 'What cron expression runs daily at midnight?', a: 'Use 0 0 * * * in your crontab. This runs at 00:00 every day.' }, { q: 'How do I run a cron job once a day?', a: 'Use 0 0 * * * for midnight, or change the hour/minute for a different time. For example, 0 3 * * * runs at 3 AM daily.' }], keywords: ['cron every day midnight', '0 0 * * *', 'daily cron', 'cron once a day'] },
  { slug: 'every-day-6am', cron: '0 6 * * *', title: 'Cron Every Day at 6 AM - Morning Schedule', h1: 'Cron Every Day at 6 AM', description: 'Schedule a cron job every day at 6 AM with 0 6 * * *. Early morning daily task automation.', explanation: 'The expression 0 6 * * * runs at 06:00 every day. Useful for morning reports, data synchronization, or cleanup tasks.', faq: [{ q: 'How do I run a cron at 6 AM every day?', a: 'Use 0 6 * * * in your crontab. This fires at 6:00 AM daily.' }], keywords: ['cron 6am', '0 6 * * *', 'cron every day 6am'] },
  { slug: 'every-day-8am', cron: '0 8 * * *', title: 'Cron Every Day at 8 AM - Expression Guide', h1: 'Cron Every Day at 8 AM', description: 'Run a cron job every day at 8 AM with 0 8 * * *. Morning automation schedule.', explanation: 'The expression 0 8 * * * runs at 08:00 every day.', faq: [{ q: 'What is the cron for 8 AM daily?', a: 'Use 0 8 * * * in your crontab.' }], keywords: ['cron 8am', '0 8 * * *'] },
  { slug: 'every-day-9am', cron: '0 9 * * *', title: 'Cron Every Day at 9 AM - Work Day Schedule', h1: 'Cron Every Day at 9 AM', description: 'Schedule a cron job every day at 9 AM with 0 9 * * *. Start-of-day automation.', explanation: 'The expression 0 9 * * * runs at 09:00 every day. Popular for sending daily digest emails or starting batch processes.', faq: [{ q: 'How do I run a cron job at 9 AM every day?', a: 'Use 0 9 * * * in your crontab. This fires at 9:00 AM daily.' }], keywords: ['cron 9am', '0 9 * * *', 'cron every day 9am'] },
  { slug: 'every-day-noon', cron: '0 12 * * *', title: 'Cron Every Day at Noon - Midday Schedule', h1: 'Cron Every Day at Noon', description: 'Run a cron job every day at noon (12:00 PM) with 0 12 * * *. Midday task automation.', explanation: 'The expression 0 12 * * * runs at 12:00 (noon) every day.', faq: [{ q: 'What cron runs at noon every day?', a: 'Use 0 12 * * * in your crontab.' }], keywords: ['cron noon', '0 12 * * *', 'cron every day noon'] },
  { slug: 'every-day-5pm', cron: '0 17 * * *', title: 'Cron Every Day at 5 PM - End of Day Schedule', h1: 'Cron Every Day at 5 PM', description: 'Run a cron job every day at 5 PM with 0 17 * * *. End-of-workday automation.', explanation: 'The expression 0 17 * * * runs at 17:00 (5 PM) every day. Cron uses 24-hour format, so 5 PM = 17.', faq: [{ q: 'How do I schedule a cron at 5 PM?', a: 'Use 0 17 * * * in your crontab. Cron uses 24-hour time, so 5 PM is hour 17.' }], keywords: ['cron 5pm', '0 17 * * *'] },
  { slug: 'every-day-9pm', cron: '0 21 * * *', title: 'Cron Every Day at 9 PM - Evening Schedule', h1: 'Cron Every Day at 9 PM', description: 'Run a cron job every day at 9 PM with 0 21 * * *. Evening task schedule.', explanation: 'The expression 0 21 * * * runs at 21:00 (9 PM) every day.', faq: [{ q: 'What cron runs at 9 PM daily?', a: 'Use 0 21 * * * in your crontab. Hour 21 is 9 PM in 24-hour format.' }], keywords: ['cron 9pm', '0 21 * * *'] },
  { slug: 'every-day-11pm', cron: '0 23 * * *', title: 'Cron Every Day at 11 PM - Late Night Schedule', h1: 'Cron Every Day at 11 PM', description: 'Run a cron job every day at 11 PM with 0 23 * * *. Late night batch processing.', explanation: 'The expression 0 23 * * * runs at 23:00 (11 PM) every day.', faq: [{ q: 'How do I run a cron at 11 PM?', a: 'Use 0 23 * * * in your crontab.' }], keywords: ['cron 11pm', '0 23 * * *'] },
  { slug: 'every-day-3am', cron: '0 3 * * *', title: 'Cron Every Day at 3 AM - Off-Peak Schedule', h1: 'Cron Every Day at 3 AM', description: 'Run a cron job every day at 3 AM with 0 3 * * *. Off-peak hours batch processing.', explanation: 'The expression 0 3 * * * runs at 03:00 every day. Popular for database backups and maintenance tasks during low-traffic hours.', faq: [{ q: 'Why run a cron at 3 AM?', a: '3 AM is typically a low-traffic period, making it ideal for resource-intensive tasks like database backups, log rotation, and data processing.' }], keywords: ['cron 3am', '0 3 * * *'] },
  { slug: 'every-day-2am', cron: '0 2 * * *', title: 'Cron Every Day at 2 AM - Maintenance Schedule', h1: 'Cron Every Day at 2 AM', description: 'Schedule a cron job at 2 AM daily with 0 2 * * *. Night maintenance window.', explanation: 'The expression 0 2 * * * runs at 02:00 every day. Common for system maintenance and backup operations.', faq: [{ q: 'What cron expression runs at 2 AM?', a: 'Use 0 2 * * * in your crontab.' }], keywords: ['cron 2am', '0 2 * * *'] },

  // === Weekday schedules ===
  { slug: 'weekdays-9am', cron: '0 9 * * 1-5', title: 'Cron Weekdays at 9 AM - Monday to Friday Schedule', h1: 'Cron Weekdays at 9 AM', description: 'Run a cron job weekdays at 9 AM with 0 9 * * 1-5. Monday through Friday schedule for work-day automation.', explanation: 'The expression 0 9 * * 1-5 runs at 9:00 AM, Monday through Friday. The 1-5 in the day-of-week field represents Monday(1) to Friday(5).', faq: [{ q: 'How do I run a cron job only on weekdays?', a: 'Use 0 9 * * 1-5 in your crontab. The 1-5 range covers Monday through Friday. Adjust the time by changing the first two fields.' }, { q: 'Does 1-5 in cron mean Monday to Friday?', a: 'Yes. In standard Unix cron, 0=Sunday, 1=Monday, 2=Tuesday, 3=Wednesday, 4=Thursday, 5=Friday, 6=Saturday. So 1-5 covers Monday through Friday.' }], keywords: ['cron weekdays', '0 9 * * 1-5', 'cron monday to friday', 'cron work days'] },
  { slug: 'weekdays-8am', cron: '0 8 * * 1-5', title: 'Cron Weekdays at 8 AM - Morning Work Schedule', h1: 'Cron Weekdays at 8 AM', description: 'Run a cron job weekdays at 8 AM with 0 8 * * 1-5. Start-of-workday automation.', explanation: 'The expression 0 8 * * 1-5 runs at 8:00 AM Monday through Friday.', faq: [{ q: 'What cron runs at 8 AM on weekdays only?', a: 'Use 0 8 * * 1-5 in your crontab.' }], keywords: ['cron weekdays 8am', '0 8 * * 1-5'] },
  { slug: 'weekdays-5pm', cron: '0 17 * * 1-5', title: 'Cron Weekdays at 5 PM - End of Work Day', h1: 'Cron Weekdays at 5 PM', description: 'Run a cron job weekdays at 5 PM with 0 17 * * 1-5. End-of-business-day tasks.', explanation: 'The expression 0 17 * * 1-5 runs at 5:00 PM (17:00) Monday through Friday.', faq: [{ q: 'How do I run a cron at 5 PM on weekdays?', a: 'Use 0 17 * * 1-5 in your crontab.' }], keywords: ['cron weekdays 5pm', '0 17 * * 1-5'] },
  { slug: 'weekdays-6pm', cron: '0 18 * * 1-5', title: 'Cron Weekdays at 6 PM - After Work Schedule', h1: 'Cron Weekdays at 6 PM', description: 'Run a cron job weekdays at 6 PM with 0 18 * * 1-5.', explanation: 'The expression 0 18 * * 1-5 runs at 6:00 PM (18:00) Monday through Friday.', faq: [{ q: 'What cron runs at 6 PM on weekdays?', a: 'Use 0 18 * * 1-5 in your crontab.' }], keywords: ['cron weekdays 6pm', '0 18 * * 1-5'] },
  { slug: 'weekdays-midnight', cron: '0 0 * * 1-5', title: 'Cron Weekdays at Midnight - Daily Maintenance', h1: 'Cron Weekdays at Midnight', description: 'Run a cron job weekdays at midnight with 0 0 * * 1-5. Night maintenance, Monday to Friday.', explanation: 'The expression 0 0 * * 1-5 runs at midnight (00:00) Monday through Friday.', faq: [{ q: 'How do I run a cron at midnight on weekdays?', a: 'Use 0 0 * * 1-5 in your crontab.' }], keywords: ['cron weekdays midnight', '0 0 * * 1-5'] },
  { slug: 'weekdays-noon', cron: '0 12 * * 1-5', title: 'Cron Weekdays at Noon - Midday Work Schedule', h1: 'Cron Weekdays at Noon', description: 'Run a cron job weekdays at noon with 0 12 * * 1-5.', explanation: 'The expression 0 12 * * 1-5 runs at 12:00 PM (noon) Monday through Friday.', faq: [{ q: 'What cron runs at noon on weekdays?', a: 'Use 0 12 * * 1-5 in your crontab.' }], keywords: ['cron weekdays noon', '0 12 * * 1-5'] },
  { slug: 'weekdays-every-hour', cron: '0 * * * 1-5', title: 'Cron Every Hour on Weekdays - Work Hours', h1: 'Cron Every Hour on Weekdays', description: 'Run a cron job every hour on weekdays with 0 * * * 1-5.', explanation: 'The expression 0 * * * 1-5 runs at the top of every hour, Monday through Friday.', faq: [{ q: 'How do I run a cron every hour but only on weekdays?', a: 'Use 0 * * * 1-5 in your crontab.' }], keywords: ['cron every hour weekdays', '0 * * * 1-5'] },

  // === Specific days ===
  { slug: 'every-monday', cron: '0 0 * * 1', title: 'Cron Every Monday - Weekly Schedule', h1: 'Cron Every Monday', description: 'Run a cron job every Monday with 0 0 * * 1. Weekly Monday schedule at midnight or any time.', explanation: 'The expression 0 0 * * 1 runs at midnight every Monday. The day-of-week field is 1, which represents Monday.', faq: [{ q: 'What cron runs every Monday?', a: 'Use 0 0 * * 1 in your crontab. Change the hour/minute for a different time, e.g., 0 9 * * 1 for 9 AM Monday.' }, { q: 'Is Monday 0 or 1 in cron?', a: 'In standard Unix cron, Monday is 1. Sunday is 0 (or 7). The range is 0-6 where 0=Sunday, 1=Monday, ..., 6=Saturday.' }], keywords: ['cron every monday', '0 0 * * 1', 'cron monday'] },
  { slug: 'every-monday-9am', cron: '0 9 * * 1', title: 'Cron Every Monday at 9 AM - Start of Week', h1: 'Cron Every Monday at 9 AM', description: 'Run a cron job every Monday at 9 AM with 0 9 * * 1.', explanation: 'The expression 0 9 * * 1 runs at 9:00 AM every Monday.', faq: [{ q: 'How do I run a cron every Monday at 9 AM?', a: 'Use 0 9 * * 1 in your crontab.' }], keywords: ['cron monday 9am', '0 9 * * 1'] },
  { slug: 'every-tuesday', cron: '0 0 * * 2', title: 'Cron Every Tuesday - Weekly Schedule', h1: 'Cron Every Tuesday', description: 'Run a cron job every Tuesday with 0 0 * * 2.', explanation: 'The expression 0 0 * * 2 runs at midnight every Tuesday. Tuesday is day 2 in cron.', faq: [{ q: 'What cron runs every Tuesday?', a: 'Use 0 0 * * 2 in your crontab.' }], keywords: ['cron every tuesday', '0 0 * * 2'] },
  { slug: 'every-wednesday', cron: '0 0 * * 3', title: 'Cron Every Wednesday - Weekly Schedule', h1: 'Cron Every Wednesday', description: 'Run a cron job every Wednesday with 0 0 * * 3.', explanation: 'The expression 0 0 * * 3 runs at midnight every Wednesday.', faq: [{ q: 'What cron runs every Wednesday?', a: 'Use 0 0 * * 3 in your crontab.' }], keywords: ['cron every wednesday', '0 0 * * 3'] },
  { slug: 'every-thursday', cron: '0 0 * * 4', title: 'Cron Every Thursday - Weekly Schedule', h1: 'Cron Every Thursday', description: 'Run a cron job every Thursday with 0 0 * * 4.', explanation: 'The expression 0 0 * * 4 runs at midnight every Thursday.', faq: [{ q: 'What cron runs every Thursday?', a: 'Use 0 0 * * 4 in your crontab.' }], keywords: ['cron every thursday', '0 0 * * 4'] },
  { slug: 'every-friday', cron: '0 0 * * 5', title: 'Cron Every Friday - End of Week Schedule', h1: 'Cron Every Friday', description: 'Run a cron job every Friday with 0 0 * * 5. End-of-week task automation.', explanation: 'The expression 0 0 * * 5 runs at midnight every Friday.', faq: [{ q: 'What cron runs every Friday?', a: 'Use 0 0 * * 5 in your crontab.' }], keywords: ['cron every friday', '0 0 * * 5'] },
  { slug: 'every-friday-5pm', cron: '0 17 * * 5', title: 'Cron Every Friday at 5 PM - Week End Report', h1: 'Cron Every Friday at 5 PM', description: 'Run a cron job every Friday at 5 PM with 0 17 * * 5.', explanation: 'The expression 0 17 * * 5 runs at 5:00 PM every Friday.', faq: [{ q: 'How do I run a cron every Friday at 5 PM?', a: 'Use 0 17 * * 5 in your crontab.' }], keywords: ['cron friday 5pm', '0 17 * * 5'] },
  { slug: 'every-saturday', cron: '0 0 * * 6', title: 'Cron Every Saturday - Weekend Schedule', h1: 'Cron Every Saturday', description: 'Run a cron job every Saturday with 0 0 * * 6.', explanation: 'The expression 0 0 * * 6 runs at midnight every Saturday. Saturday is day 6 in cron.', faq: [{ q: 'What cron runs every Saturday?', a: 'Use 0 0 * * 6 in your crontab.' }], keywords: ['cron every saturday', '0 0 * * 6'] },
  { slug: 'every-sunday', cron: '0 0 * * 0', title: 'Cron Every Sunday - Weekend Schedule', h1: 'Cron Every Sunday', description: 'Run a cron job every Sunday with 0 0 * * 0. Weekly Sunday schedule.', explanation: 'The expression 0 0 * * 0 runs at midnight every Sunday. Sunday is day 0 (or 7) in cron.', faq: [{ q: 'Is Sunday 0 or 7 in cron?', a: 'Both work. Sunday can be represented as 0 or 7 in the day-of-week field. Use whichever you prefer.' }], keywords: ['cron every sunday', '0 0 * * 0'] },
  { slug: 'every-sunday-noon', cron: '0 12 * * 0', title: 'Cron Every Sunday at Noon', h1: 'Cron Every Sunday at Noon', description: 'Run a cron job every Sunday at noon with 0 12 * * 0.', explanation: 'The expression 0 12 * * 0 runs at 12:00 PM every Sunday.', faq: [{ q: 'What cron runs every Sunday at noon?', a: 'Use 0 12 * * 0 in your crontab.' }], keywords: ['cron sunday noon', '0 12 * * 0'] },
  { slug: 'weekends', cron: '0 0 * * 0,6', title: 'Cron Weekends - Saturday and Sunday Schedule', h1: 'Cron Weekends (Saturday & Sunday)', description: 'Run a cron job on weekends with 0 0 * * 0,6. Saturday and Sunday schedule.', explanation: 'The expression 0 0 * * 0,6 uses a comma-separated list (0,6) to match both Sunday (0) and Saturday (6).', faq: [{ q: 'How do I run a cron only on weekends?', a: 'Use 0 0 * * 0,6 in your crontab. The 0,6 means "Sunday OR Saturday".' }], keywords: ['cron weekends', '0 0 * * 0,6', 'cron saturday sunday'] },
  { slug: 'weekends-9am', cron: '0 9 * * 0,6', title: 'Cron Weekends at 9 AM', h1: 'Cron Weekends at 9 AM', description: 'Run a cron job on weekends at 9 AM with 0 9 * * 0,6.', explanation: 'The expression 0 9 * * 0,6 runs at 9:00 AM on Saturday and Sunday.', faq: [{ q: 'What cron runs at 9 AM on weekends?', a: 'Use 0 9 * * 0,6 in your crontab.' }], keywords: ['cron weekends 9am', '0 9 * * 0,6'] },

  // === Monthly schedules ===
  { slug: 'first-of-month', cron: '0 0 1 * *', title: 'Cron First Day of Month - Monthly Schedule', h1: 'Cron First Day of Every Month', description: 'Run a cron job on the 1st of every month with 0 0 1 * * . Monthly report and billing schedule.', explanation: 'The expression 0 0 1 * * runs at midnight on the 1st day of every month. The day-of-month field is set to 1.', faq: [{ q: 'How do I run a cron on the first of every month?', a: 'Use 0 0 1 * * in your crontab. This fires at midnight on the 1st of each month.' }, { q: 'Can I run a cron on the first business day of the month?', a: 'Cron does not natively support business day logic. Use 0 0 1-3 * * and add logic in your script to check if the day is a weekday.' }], keywords: ['cron first of month', '0 0 1 * *', 'cron monthly', 'cron 1st'] },
  { slug: '15th-of-month', cron: '0 0 15 * *', title: 'Cron 15th of Every Month - Mid-Month Schedule', h1: 'Cron 15th of Every Month', description: 'Run a cron job on the 15th of every month with 0 0 15 * *.', explanation: 'The expression 0 0 15 * * runs at midnight on the 15th of every month.', faq: [{ q: 'What cron runs on the 15th of each month?', a: 'Use 0 0 15 * * in your crontab.' }], keywords: ['cron 15th of month', '0 0 15 * *'] },
  { slug: 'last-day-of-month', cron: '0 0 28-31 * *', title: 'Cron Last Day of Month - Month End Schedule', h1: 'Cron Last Day of Month', description: 'Run a cron job on the last day of every month with 0 0 28-31 * *.', explanation: 'The expression 0 0 28-31 * * runs at midnight on days 28-31. Add logic in your script to verify it is actually the last day.', faq: [{ q: 'How do I run a cron on the last day of the month?', a: 'Use 0 0 28-31 * * and add date checking in your script: if [ "$(date +%d -d tomorrow)" = "01" ]; then your_command; fi' }], keywords: ['cron last day of month', 'cron month end'] },
  { slug: 'every-month', cron: '0 0 1 * *', title: 'Cron Every Month - Monthly Schedule', h1: 'Cron Every Month', description: 'Run a cron job monthly with 0 0 1 * * . Monthly automation schedule.', explanation: 'The expression 0 0 1 * * runs monthly at midnight on the 1st.', faq: [{ q: 'How do I schedule a monthly cron job?', a: 'Use 0 0 1 * * for the 1st of each month at midnight, or adjust the day/hour/minute as needed.' }], keywords: ['cron every month', 'monthly cron'] },
  { slug: 'every-quarter', cron: '0 0 1 1,4,7,10 *', title: 'Cron Every Quarter - Quarterly Schedule', h1: 'Cron Every Quarter', description: 'Run a cron job quarterly (every 3 months) with 0 0 1 1,4,7,10 *.', explanation: 'The expression 0 0 1 1,4,7,10 * runs at midnight on the 1st of January, April, July, and October.', faq: [{ q: 'How do I run a cron every quarter?', a: 'Use 0 0 1 1,4,7,10 * in your crontab. This runs on the 1st of Jan, Apr, Jul, and Oct.' }], keywords: ['cron quarterly', 'every 3 months cron'] },
  { slug: 'every-6-months', cron: '0 0 1 1,7 *', title: 'Cron Every 6 Months - Semi-Annual Schedule', h1: 'Cron Every 6 Months', description: 'Run a cron job every 6 months with 0 0 1 1,7 *.', explanation: 'The expression 0 0 1 1,7 * runs at midnight on January 1st and July 1st.', faq: [{ q: 'What cron runs every 6 months?', a: 'Use 0 0 1 1,7 * in your crontab.' }], keywords: ['cron every 6 months', 'semi annual cron'] },
  { slug: 'every-year', cron: '0 0 1 1 *', title: 'Cron Every Year - Annual Schedule', h1: 'Cron Every Year (January 1st)', description: 'Run a cron job annually on January 1st with 0 0 1 1 *.', explanation: 'The expression 0 0 1 1 * runs at midnight on January 1st every year.', faq: [{ q: 'How do I run a cron once a year?', a: 'Use 0 0 1 1 * for January 1st at midnight. Adjust the month and day fields for other dates.' }], keywords: ['cron every year', 'annual cron', 'yearly cron'] },

  // === Specific minute offsets ===
  { slug: 'every-hour-at-30', cron: '30 * * * *', title: 'Cron Every Hour at Minute 30', h1: 'Cron Every Hour at :30', description: 'Run a cron every hour at minute 30 with 30 * * * *.', explanation: 'The expression 30 * * * * runs at :30 past every hour (00:30, 01:30, 02:30, etc.).', faq: [{ q: 'How do I run a cron at :30 every hour?', a: 'Use 30 * * * * in your crontab.' }], keywords: ['cron minute 30', '30 * * * *'] },
  { slug: 'every-hour-at-15', cron: '15 * * * *', title: 'Cron Every Hour at Minute 15', h1: 'Cron Every Hour at :15', description: 'Run a cron every hour at minute 15 with 15 * * * *.', explanation: 'The expression 15 * * * * runs at :15 past every hour.', faq: [{ q: 'What cron runs at :15 every hour?', a: 'Use 15 * * * * in your crontab.' }], keywords: ['cron minute 15', '15 * * * *'] },
  { slug: 'every-hour-at-45', cron: '45 * * * *', title: 'Cron Every Hour at Minute 45', h1: 'Cron Every Hour at :45', description: 'Run a cron every hour at minute 45 with 45 * * * *.', explanation: 'The expression 45 * * * * runs at :45 past every hour.', faq: [{ q: 'What cron runs at :45 every hour?', a: 'Use 45 * * * * in your crontab.' }], keywords: ['cron minute 45', '45 * * * *'] },

  // === Multiple times per day ===
  { slug: 'twice-daily-9am-9pm', cron: '0 9,21 * * *', title: 'Cron Twice Daily at 9 AM and 9 PM', h1: 'Cron Twice Daily (9 AM & 9 PM)', description: 'Run a cron twice daily at 9 AM and 9 PM with 0 9,21 * * *.', explanation: 'The expression 0 9,21 * * * uses a comma-separated list to specify two hours: 9 (9 AM) and 21 (9 PM).', faq: [{ q: 'How do I run a cron twice a day?', a: 'Use comma-separated values in the hour field. For example, 0 9,21 * * * runs at 9 AM and 9 PM.' }], keywords: ['cron twice daily', '0 9,21 * * *'] },
  { slug: 'three-times-daily', cron: '0 8,16,0 * * *', title: 'Cron Three Times Daily', h1: 'Cron Three Times Daily', description: 'Run a cron three times a day at midnight, 8 AM, and 4 PM with 0 0,8,16 * * *.', explanation: 'The expression 0 0,8,16 * * * runs at midnight, 8 AM, and 4 PM daily.', faq: [{ q: 'How do I run a cron 3 times a day?', a: 'Use 0 0,8,16 * * * in your crontab. Adjust the hours to your desired times.' }], keywords: ['cron three times daily', '0 0,8,16 * * *'] },
  { slug: 'four-times-daily', cron: '0 0,6,12,18 * * *', title: 'Cron Four Times Daily', h1: 'Cron Four Times Daily', description: 'Run a cron 4 times a day with 0 0,6,12,18 * * *. Every 6 hours at midnight, 6AM, noon, 6PM.', explanation: 'The expression 0 0,6,12,18 * * * runs at midnight, 6 AM, noon, and 6 PM daily.', faq: [{ q: 'What cron runs 4 times a day?', a: 'Use 0 0,6,12,18 * * * in your crontab.' }], keywords: ['cron four times daily', '0 0,6,12,18 * * *'] },

  // === Specific date patterns ===
  { slug: 'every-january', cron: '0 0 1 1 *', title: 'Cron Every January - Annual January Schedule', h1: 'Cron Every January', description: 'Run a cron job every January 1st with 0 0 1 1 *.', explanation: 'The expression 0 0 1 1 * runs at midnight on January 1st every year.', faq: [{ q: 'How do I run a cron every January?', a: 'Use 0 0 1 1 * in your crontab. Change the day field for a different date in January.' }], keywords: ['cron january', '0 0 1 1 *'] },
  { slug: 'every-monday-wednesday-friday', cron: '0 0 * * 1,3,5', title: 'Cron Monday Wednesday Friday - MWF Schedule', h1: 'Cron Monday, Wednesday, Friday', description: 'Run a cron on Monday, Wednesday, and Friday with 0 0 * * 1,3,5.', explanation: 'The expression 0 0 * * 1,3,5 uses comma-separated day values: Monday(1), Wednesday(3), Friday(5).', faq: [{ q: 'How do I run a cron on MWF?', a: 'Use 0 0 * * 1,3,5 in your crontab.' }], keywords: ['cron monday wednesday friday', 'MWF cron', '0 0 * * 1,3,5'] },
  { slug: 'every-tuesday-thursday', cron: '0 0 * * 2,4', title: 'Cron Tuesday Thursday - TTh Schedule', h1: 'Cron Tuesday and Thursday', description: 'Run a cron on Tuesday and Thursday with 0 0 * * 2,4.', explanation: 'The expression 0 0 * * 2,4 uses comma-separated day values: Tuesday(2) and Thursday(4).', faq: [{ q: 'How do I run a cron on Tuesday and Thursday?', a: 'Use 0 0 * * 2,4 in your crontab.' }], keywords: ['cron tuesday thursday', 'TTh cron', '0 0 * * 2,4'] },

  // === Cron syntax explainers ===
  { slug: 'cron-asterisk', cron: '* * * * *', title: 'What Does * Mean in Cron? - Asterisk Wildcard', h1: 'Cron Asterisk (*) Wildcard', description: 'The asterisk (*) in cron means "every". It matches all possible values for that field. Learn how * works in each cron field.', explanation: 'In cron, the asterisk (*) is a wildcard that matches every possible value. * in the minute field means "every minute". * in the hour field means "every hour".', faq: [{ q: 'What does * mean in cron?', a: 'The asterisk (*) means "every" or "any value". In the minute field, * means every minute (0-59). In the hour field, * means every hour (0-23).' }, { q: 'What is the difference between * and */1?', a: 'They are equivalent. */1 means "every 1 unit", which is the same as * (every unit). Use * for clarity.' }], keywords: ['cron asterisk', 'cron star meaning', 'what does * mean in cron'] },
  { slug: 'cron-step-operator', cron: '*/5 * * * *', title: 'Cron Step Operator (*/N) - Complete Guide', h1: 'Cron Step Operator (*/N)', description: 'Learn how the cron step operator */N works. Use */5 for every 5 units, */10 for every 10 units. Complete syntax guide.', explanation: 'The step operator */N means "every Nth value". */5 in the minute field means minutes 0, 5, 10, 15, etc. */2 in the hour field means hours 0, 2, 4, 6, etc.', faq: [{ q: 'What does */5 mean in cron?', a: '*/5 is the step operator. In the minute field, it means "every 5 minutes" (0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55).' }, { q: 'Can I use step values in any field?', a: 'Yes. */5 in minutes = every 5 min. */2 in hours = every 2 hours. */3 in day-of-month = every 3rd day.' }], keywords: ['cron step operator', 'cron */5', 'cron every N'] },
  { slug: 'cron-range-operator', cron: '0 9 * * 1-5', title: 'Cron Range Operator (N-M) - Complete Guide', h1: 'Cron Range Operator (N-M)', description: 'Learn how the cron range operator N-M works. 1-5 means Monday to Friday. 9-17 means 9 AM to 5 PM.', explanation: 'The range operator N-M matches all values from N to M inclusive. 1-5 in the day-of-week field means Monday through Friday. 9-17 in the hour field means 9 AM through 5 PM.', faq: [{ q: 'What does 1-5 mean in cron?', a: '1-5 is a range. In the day-of-week field, it means Monday(1) through Friday(5). In the hour field, 9-17 would mean 9 AM through 5 PM.' }], keywords: ['cron range', 'cron 1-5', 'cron dash operator'] },
  { slug: 'cron-list-operator', cron: '0 0 * * 0,6', title: 'Cron List Operator (N,M) - Complete Guide', h1: 'Cron List Operator (N,M)', description: 'Learn how the cron list operator (comma) works. 0,6 means Sunday and Saturday. Multiple specific values.', explanation: 'The list operator (comma) matches specific individual values. 0,6 in the day-of-week field means Sunday OR Saturday. 9,12,17 in the hour field means 9 AM, noon, or 5 PM.', faq: [{ q: 'How do I specify multiple values in cron?', a: 'Use commas to separate values. For example, 0,6 in the day-of-week field matches Sunday and Saturday.' }], keywords: ['cron comma', 'cron list', 'cron multiple values'] },

  // === More minute intervals ===
  { slug: 'every-2-minutes', cron: '*/2 * * * *', title: 'Cron Every 2 Minutes - Expression & Examples', h1: 'Cron Every 2 Minutes', description: 'Run a cron job every 2 minutes with */2 * * * *. Fast polling schedule for monitoring and syncing.', explanation: 'The expression */2 * * * * triggers at every even-numbered minute: 0, 2, 4, 6, ..., 58 of every hour.', faq: [{ q: 'What cron runs every 2 minutes?', a: 'Use */2 * * * * in your crontab.' }, { q: 'Is every 2 minutes too frequent?', a: 'It depends on your task. For monitoring or polling, it is common. Ensure each run completes within 2 minutes to avoid overlap.' }], keywords: ['cron every 2 minutes', '*/2 * * * *'] },
  { slug: 'every-3-minutes', cron: '*/3 * * * *', title: 'Cron Every 3 Minutes - Schedule Guide', h1: 'Cron Every 3 Minutes', description: 'Schedule a cron job every 3 minutes with */3 * * * *. Moderate polling frequency.', explanation: 'The expression */3 * * * * triggers at minute 0, 3, 6, 9, ..., 57 of every hour.', faq: [{ q: 'How do I run a cron every 3 minutes?', a: 'Use */3 * * * * in your crontab.' }], keywords: ['cron every 3 minutes', '*/3 * * * *'] },
  { slug: 'every-7-minutes', cron: '*/7 * * * *', title: 'Cron Every 7 Minutes - Unusual Interval', h1: 'Cron Every 7 Minutes', description: 'Run a cron job every 7 minutes with */7 * * * *. Useful for staggered schedules.', explanation: 'The expression */7 * * * * triggers at minute 0, 7, 14, 21, 28, 35, 42, 49, 56 of every hour.', faq: [{ q: 'Why use every 7 minutes?', a: 'Unusual intervals like */7 help stagger jobs to avoid resource spikes that occur when many jobs run at even boundaries.' }], keywords: ['cron every 7 minutes', '*/7 * * * *'] },
  { slug: 'every-25-minutes', cron: '*/25 * * * *', title: 'Cron Every 25 Minutes - Custom Interval', h1: 'Cron Every 25 Minutes', description: 'Run a cron job every 25 minutes with */25 * * * *.', explanation: 'The expression */25 * * * * triggers at minute 0, 25, and 50 of every hour.', faq: [{ q: 'What cron runs every 25 minutes?', a: 'Use */25 * * * * in your crontab.' }], keywords: ['cron every 25 minutes', '*/25 * * * *'] },

  // === More hour intervals ===
  { slug: 'every-5-hours', cron: '0 */5 * * *', title: 'Cron Every 5 Hours - Expression Guide', h1: 'Cron Every 5 Hours', description: 'Run a cron job every 5 hours with 0 */5 * * *. Fires at 00:00, 05:00, 10:00, 15:00, 20:00.', explanation: 'The expression 0 */5 * * * runs at 00:00, 05:00, 10:00, 15:00, and 20:00 daily.', faq: [{ q: 'What cron runs every 5 hours?', a: 'Use 0 */5 * * * in your crontab.' }], keywords: ['cron every 5 hours', '0 */5 * * *'] },
  { slug: 'every-9-hours', cron: '0 */9 * * *', title: 'Cron Every 9 Hours', h1: 'Cron Every 9 Hours', description: 'Run a cron job every 9 hours with 0 */9 * * *.', explanation: 'The expression 0 */9 * * * runs at 00:00 and 09:00 and 18:00 daily.', faq: [{ q: 'What cron runs every 9 hours?', a: 'Use 0 */9 * * * in your crontab.' }], keywords: ['cron every 9 hours', '0 */9 * * *'] },
  { slug: 'every-10-hours', cron: '0 */10 * * *', title: 'Cron Every 10 Hours', h1: 'Cron Every 10 Hours', description: 'Run a cron job every 10 hours with 0 */10 * * *.', explanation: 'The expression 0 */10 * * * runs at 00:00, 10:00, and 20:00 daily.', faq: [{ q: 'How do I run a cron every 10 hours?', a: 'Use 0 */10 * * * in your crontab.' }], keywords: ['cron every 10 hours', '0 */10 * * *'] },

  // === More daily specific times ===
  { slug: 'every-day-1am', cron: '0 1 * * *', title: 'Cron Every Day at 1 AM', h1: 'Cron Every Day at 1 AM', description: 'Run a cron job every day at 1 AM with 0 1 * * *. Early morning automation.', explanation: 'The expression 0 1 * * * runs at 01:00 every day.', faq: [{ q: 'What cron runs at 1 AM daily?', a: 'Use 0 1 * * * in your crontab.' }], keywords: ['cron 1am', '0 1 * * *'] },
  { slug: 'every-day-4am', cron: '0 4 * * *', title: 'Cron Every Day at 4 AM', h1: 'Cron Every Day at 4 AM', description: 'Run a cron job every day at 4 AM with 0 4 * * *. Off-peak processing.', explanation: 'The expression 0 4 * * * runs at 04:00 every day.', faq: [{ q: 'What cron runs at 4 AM?', a: 'Use 0 4 * * * in your crontab.' }], keywords: ['cron 4am', '0 4 * * *'] },
  { slug: 'every-day-7am', cron: '0 7 * * *', title: 'Cron Every Day at 7 AM', h1: 'Cron Every Day at 7 AM', description: 'Run a cron job every day at 7 AM with 0 7 * * *.', explanation: 'The expression 0 7 * * * runs at 07:00 every day.', faq: [{ q: 'How do I run a cron at 7 AM?', a: 'Use 0 7 * * * in your crontab.' }], keywords: ['cron 7am', '0 7 * * *'] },
  { slug: 'every-day-10am', cron: '0 10 * * *', title: 'Cron Every Day at 10 AM', h1: 'Cron Every Day at 10 AM', description: 'Run a cron job every day at 10 AM with 0 10 * * *.', explanation: 'The expression 0 10 * * * runs at 10:00 every day.', faq: [{ q: 'What cron runs at 10 AM daily?', a: 'Use 0 10 * * * in your crontab.' }], keywords: ['cron 10am', '0 10 * * *'] },
  { slug: 'every-day-1pm', cron: '0 13 * * *', title: 'Cron Every Day at 1 PM', h1: 'Cron Every Day at 1 PM', description: 'Run a cron job every day at 1 PM with 0 13 * * *. Afternoon schedule.', explanation: 'The expression 0 13 * * * runs at 13:00 (1 PM) every day. Cron uses 24-hour format.', faq: [{ q: 'How do I run a cron at 1 PM?', a: 'Use 0 13 * * * in your crontab. Hour 13 is 1 PM in 24-hour time.' }], keywords: ['cron 1pm', '0 13 * * *'] },
  { slug: 'every-day-2pm', cron: '0 14 * * *', title: 'Cron Every Day at 2 PM', h1: 'Cron Every Day at 2 PM', description: 'Run a cron job every day at 2 PM with 0 14 * * *.', explanation: 'The expression 0 14 * * * runs at 14:00 (2 PM) every day.', faq: [{ q: 'What cron runs at 2 PM daily?', a: 'Use 0 14 * * * in your crontab.' }], keywords: ['cron 2pm', '0 14 * * *'] },
  { slug: 'every-day-3pm', cron: '0 15 * * *', title: 'Cron Every Day at 3 PM', h1: 'Cron Every Day at 3 PM', description: 'Run a cron job every day at 3 PM with 0 15 * * *.', explanation: 'The expression 0 15 * * * runs at 15:00 (3 PM) every day.', faq: [{ q: 'How do I schedule a cron at 3 PM?', a: 'Use 0 15 * * * in your crontab.' }], keywords: ['cron 3pm', '0 15 * * *'] },
  { slug: 'every-day-4pm', cron: '0 16 * * *', title: 'Cron Every Day at 4 PM', h1: 'Cron Every Day at 4 PM', description: 'Run a cron job every day at 4 PM with 0 16 * * *.', explanation: 'The expression 0 16 * * * runs at 16:00 (4 PM) every day.', faq: [{ q: 'What cron runs at 4 PM?', a: 'Use 0 16 * * * in your crontab.' }], keywords: ['cron 4pm', '0 16 * * *'] },
  { slug: 'every-day-6pm', cron: '0 18 * * *', title: 'Cron Every Day at 6 PM', h1: 'Cron Every Day at 6 PM', description: 'Run a cron job every day at 6 PM with 0 18 * * *.', explanation: 'The expression 0 18 * * * runs at 18:00 (6 PM) every day.', faq: [{ q: 'How do I run a cron at 6 PM?', a: 'Use 0 18 * * * in your crontab.' }], keywords: ['cron 6pm', '0 18 * * *'] },
  { slug: 'every-day-7pm', cron: '0 19 * * *', title: 'Cron Every Day at 7 PM', h1: 'Cron Every Day at 7 PM', description: 'Run a cron job every day at 7 PM with 0 19 * * *.', explanation: 'The expression 0 19 * * * runs at 19:00 (7 PM) every day.', faq: [{ q: 'What cron runs at 7 PM?', a: 'Use 0 19 * * * in your crontab.' }], keywords: ['cron 7pm', '0 19 * * *'] },
  { slug: 'every-day-8pm', cron: '0 20 * * *', title: 'Cron Every Day at 8 PM', h1: 'Cron Every Day at 8 PM', description: 'Run a cron job every day at 8 PM with 0 20 * * *.', explanation: 'The expression 0 20 * * * runs at 20:00 (8 PM) every day.', faq: [{ q: 'What cron runs at 8 PM?', a: 'Use 0 20 * * * in your crontab.' }], keywords: ['cron 8pm', '0 20 * * *'] },
  { slug: 'every-day-10pm', cron: '0 22 * * *', title: 'Cron Every Day at 10 PM', h1: 'Cron Every Day at 10 PM', description: 'Run a cron job every day at 10 PM with 0 22 * * *.', explanation: 'The expression 0 22 * * * runs at 22:00 (10 PM) every day.', faq: [{ q: 'How do I run a cron at 10 PM?', a: 'Use 0 22 * * * in your crontab.' }], keywords: ['cron 10pm', '0 22 * * *'] },

  // === More day+time combos ===
  { slug: 'every-monday-8am', cron: '0 8 * * 1', title: 'Cron Every Monday at 8 AM', h1: 'Cron Every Monday at 8 AM', description: 'Run a cron job every Monday at 8 AM with 0 8 * * 1.', explanation: 'The expression 0 8 * * 1 runs at 8:00 AM every Monday.', faq: [{ q: 'How do I run a cron every Monday at 8 AM?', a: 'Use 0 8 * * 1 in your crontab.' }], keywords: ['cron monday 8am', '0 8 * * 1'] },
  { slug: 'every-tuesday-2pm', cron: '0 14 * * 2', title: 'Cron Every Tuesday at 2 PM', h1: 'Cron Every Tuesday at 2 PM', description: 'Run a cron job every Tuesday at 2 PM with 0 14 * * 2.', explanation: 'The expression 0 14 * * 2 runs at 2:00 PM every Tuesday.', faq: [{ q: 'What cron runs every Tuesday at 2 PM?', a: 'Use 0 14 * * 2 in your crontab.' }], keywords: ['cron tuesday 2pm', '0 14 * * 2'] },
  { slug: 'every-wednesday-10am', cron: '0 10 * * 3', title: 'Cron Every Wednesday at 10 AM', h1: 'Cron Every Wednesday at 10 AM', description: 'Run a cron job every Wednesday at 10 AM with 0 10 * * 3.', explanation: 'The expression 0 10 * * 3 runs at 10:00 AM every Wednesday.', faq: [{ q: 'How do I run a cron every Wednesday at 10 AM?', a: 'Use 0 10 * * 3 in your crontab.' }], keywords: ['cron wednesday 10am', '0 10 * * 3'] },
  { slug: 'every-thursday-3pm', cron: '0 15 * * 4', title: 'Cron Every Thursday at 3 PM', h1: 'Cron Every Thursday at 3 PM', description: 'Run a cron job every Thursday at 3 PM with 0 15 * * 4.', explanation: 'The expression 0 15 * * 4 runs at 3:00 PM every Thursday.', faq: [{ q: 'What cron runs every Thursday at 3 PM?', a: 'Use 0 15 * * 4 in your crontab.' }], keywords: ['cron thursday 3pm', '0 15 * * 4'] },
  { slug: 'every-friday-noon', cron: '0 12 * * 5', title: 'Cron Every Friday at Noon', h1: 'Cron Every Friday at Noon', description: 'Run a cron job every Friday at noon with 0 12 * * 5.', explanation: 'The expression 0 12 * * 5 runs at 12:00 PM every Friday.', faq: [{ q: 'How do I run a cron every Friday at noon?', a: 'Use 0 12 * * 5 in your crontab.' }], keywords: ['cron friday noon', '0 12 * * 5'] },
  { slug: 'every-saturday-9am', cron: '0 9 * * 6', title: 'Cron Every Saturday at 9 AM', h1: 'Cron Every Saturday at 9 AM', description: 'Run a cron job every Saturday at 9 AM with 0 9 * * 6.', explanation: 'The expression 0 9 * * 6 runs at 9:00 AM every Saturday.', faq: [{ q: 'What cron runs every Saturday at 9 AM?', a: 'Use 0 9 * * 6 in your crontab.' }], keywords: ['cron saturday 9am', '0 9 * * 6'] },
  { slug: 'every-sunday-6pm', cron: '0 18 * * 0', title: 'Cron Every Sunday at 6 PM', h1: 'Cron Every Sunday at 6 PM', description: 'Run a cron job every Sunday at 6 PM with 0 18 * * 0.', explanation: 'The expression 0 18 * * 0 runs at 6:00 PM every Sunday.', faq: [{ q: 'How do I run a cron every Sunday at 6 PM?', a: 'Use 0 18 * * 0 in your crontab.' }], keywords: ['cron sunday 6pm', '0 18 * * 0'] },
  { slug: 'every-saturday-8am', cron: '0 8 * * 6', title: 'Cron Every Saturday at 8 AM', h1: 'Cron Every Saturday at 8 AM', description: 'Run a cron job every Saturday at 8 AM with 0 8 * * 6.', explanation: 'The expression 0 8 * * 6 runs at 8:00 AM every Saturday.', faq: [{ q: 'What cron runs every Saturday at 8 AM?', a: 'Use 0 8 * * 6 in your crontab.' }], keywords: ['cron saturday 8am', '0 8 * * 6'] },

  // === Every N days ===
  { slug: 'every-2-days', cron: '0 0 */2 * *', title: 'Cron Every 2 Days - Alternate Day Schedule', h1: 'Cron Every 2 Days', description: 'Run a cron job every 2 days with 0 0 */2 * *.', explanation: 'The expression 0 0 */2 * * uses the step operator in the day-of-month field. It runs at midnight on days 1, 3, 5, 7, etc.', faq: [{ q: 'How do I run a cron every other day?', a: 'Use 0 0 */2 * * in your crontab. This runs at midnight on alternate days.' }], keywords: ['cron every 2 days', '0 0 */2 * *', 'cron every other day'] },
  { slug: 'every-3-days', cron: '0 0 */3 * *', title: 'Cron Every 3 Days', h1: 'Cron Every 3 Days', description: 'Run a cron job every 3 days with 0 0 */3 * *.', explanation: 'The expression 0 0 */3 * * runs at midnight on days 1, 4, 7, 10, etc.', faq: [{ q: 'What cron runs every 3 days?', a: 'Use 0 0 */3 * * in your crontab.' }], keywords: ['cron every 3 days', '0 0 */3 * *'] },
  { slug: 'every-5-days', cron: '0 0 */5 * *', title: 'Cron Every 5 Days', h1: 'Cron Every 5 Days', description: 'Run a cron job every 5 days with 0 0 */5 * *.', explanation: 'The expression 0 0 */5 * * runs at midnight on days 1, 6, 11, 16, 21, 26.', faq: [{ q: 'How do I run a cron every 5 days?', a: 'Use 0 0 */5 * * in your crontab.' }], keywords: ['cron every 5 days', '0 0 */5 * *'] },

  // === Cron syntax guides ===
  { slug: 'cron-field-order', cron: '* * * * *', title: 'Cron Field Order - 5 Fields Explained', h1: 'Cron Field Order Explained', description: 'Understand the 5 cron fields: minute, hour, day of month, month, day of week. Complete reference with examples.', explanation: 'A cron expression has 5 fields separated by spaces: minute (0-59), hour (0-23), day of month (1-31), month (1-12), day of week (0-6, where 0=Sunday).', faq: [{ q: 'What are the 5 fields in a cron expression?', a: 'From left to right: minute (0-59), hour (0-23), day of month (1-31), month (1-12), day of week (0-6).' }, { q: 'Which field is which in cron?', a: 'The order is: minute hour day-of-month month day-of-week. A mnemonic: "M H DOM MON DOW".' }], keywords: ['cron field order', 'cron 5 fields', 'cron field meanings'] },
  { slug: 'cron-special-characters', cron: '*/5 * * * *', title: 'Cron Special Characters - * , - / Explained', h1: 'Cron Special Characters', description: 'Learn cron special characters: asterisk (*), comma (,), hyphen (-), slash (/). Complete syntax reference.', explanation: 'Cron supports 4 special characters: * (any value), , (list separator), - (range), / (step). For example, */5 means every 5, 1-5 means 1 through 5, 0,6 means 0 and 6.', faq: [{ q: 'What special characters does cron support?', a: 'Four: * (wildcard/any), , (list of values), - (range), / (step). Combined: */5,15-45,1,15 means every 5 OR 15-45 OR 1 OR 15.' }], keywords: ['cron special characters', 'cron symbols', 'cron syntax'] },
  { slug: 'cron-at-shortcuts', cron: '@daily', title: 'Cron @ Shortcuts - @daily @hourly @reboot', h1: 'Cron @ Shortcuts', description: 'Learn cron shorthand aliases: @daily, @hourly, @weekly, @monthly, @yearly, @reboot. Easier than remembering expressions.', explanation: 'Cron provides shortcuts: @yearly (0 0 1 1 *), @monthly (0 0 1 * *), @weekly (0 0 * * 0), @daily (0 0 * * *), @hourly (0 * * * *), @reboot (runs at startup).', faq: [{ q: 'What are cron @ shortcuts?', a: 'Instead of writing 0 0 * * *, you can write @daily. Other shortcuts: @hourly, @daily, @weekly, @monthly, @yearly, @reboot.' }, { q: 'Does @reboot work on all systems?', a: 'It works on most Linux systems with Vixie Cron (the default). It may not work on all cron implementations.' }], keywords: ['cron @daily', 'cron shortcuts', '@hourly @weekly @monthly'] },
  { slug: 'cron-min-max-values', cron: '0-59 0-23 1-31 1-12 0-6', title: 'Cron Field Ranges - Min and Max Values', h1: 'Cron Field Value Ranges', description: 'Reference for cron field ranges: minutes 0-59, hours 0-23, day of month 1-31, months 1-12, day of week 0-6.', explanation: 'Each cron field has a valid range: minute (0-59), hour (0-23), day of month (1-31), month (1-12), day of week (0-6 where 0=Sunday). Some implementations allow 7 for Sunday.', faq: [{ q: 'What is the range of the minute field?', a: '0 to 59. You cannot use 60 or higher in the minute field.' }, { q: 'Can month names be used in cron?', a: 'Some implementations support names: jan, feb, mar, etc. Similarly, day names: sun, mon, tue, etc. Not all cron daemons support this.' }], keywords: ['cron field range', 'cron values', 'cron min max'] },

  // === Use case pages ===
  { slug: 'cron-database-backup', cron: '0 2 * * *', title: 'Cron for Database Backup - Daily Backup Schedule', h1: 'Cron Database Backup Schedule', description: 'Schedule daily database backups with cron. Expression 0 2 * * * runs at 2 AM daily for automated MySQL, PostgreSQL, MongoDB backups.', explanation: 'Use 0 2 * * * to run database backups at 2 AM daily. This ensures backups happen during low-traffic hours. Example: 0 2 * * * mysqldump -u root mydb > /backup/mydb_$(date +\%F).sql', faq: [{ q: 'What cron should I use for database backups?', a: '0 2 * * * runs daily at 2 AM. For hourly backups, use 0 * * * *. For weekly, use 0 2 * * 0.' }, { q: 'How do I add date to backup filename in cron?', a: 'Use $(date +\\%F) in your command. The percent sign must be escaped with backslash in crontab.' }], keywords: ['cron database backup', 'cron mysql backup', 'cron postgresql backup'] },
  { slug: 'cron-log-rotation', cron: '0 0 * * *', title: 'Cron for Log Rotation - Daily Log Management', h1: 'Cron Log Rotation Schedule', description: 'Automate log rotation with cron. Daily schedule to compress, archive, and clean up old log files.', explanation: 'Use 0 0 * * * to trigger log rotation at midnight daily. Most Linux systems use logrotate with its own cron entry in /etc/cron.daily/.', faq: [{ q: 'How do I set up log rotation with cron?', a: 'Most systems handle this via /etc/cron.daily/logrotate. For custom rotation, add: 0 0 * * * /usr/sbin/logrotate /etc/logrotate.conf' }], keywords: ['cron log rotation', 'cron log cleanup', 'cron rotate logs'] },
  { slug: 'cron-cache-clear', cron: '0 */6 * * *', title: 'Cron for Cache Clearing - Clear Cache Every 6 Hours', h1: 'Cron Cache Clear Schedule', description: 'Schedule automatic cache clearing with cron. Run 0 */6 * * * to flush caches every 6 hours.', explanation: 'Use 0 */6 * * * to clear caches at midnight, 6 AM, noon, and 6 PM. Adjust frequency based on your cache invalidation needs.', faq: [{ q: 'How do I clear cache with cron?', a: 'Add 0 */6 * * * rm -rf /path/to/cache/* to your crontab. For Redis: 0 */6 * * * redis-cli FLUSHALL.' }], keywords: ['cron clear cache', 'cron cache flush', 'cron redis flush'] },
  { slug: 'cron-health-check', cron: '*/5 * * * *', title: 'Cron Health Check - Monitor Every 5 Minutes', h1: 'Cron Health Check Schedule', description: 'Set up server health checks with cron. Run */5 * * * * to monitor uptime, disk space, and service status.', explanation: 'Use */5 * * * * to run health checks every 5 minutes. The script can check HTTP endpoints, disk space, memory usage, and service status.', faq: [{ q: 'How do I set up a cron health check?', a: 'Use */5 * * * * curl -f http://localhost:8080/health || echo "Service down" | mail -s "Alert" admin@example.com' }], keywords: ['cron health check', 'cron monitoring', 'cron server monitoring'] },
  { slug: 'cron-ssl-renewal', cron: '0 0 1 * *', title: 'Cron SSL Certificate Renewal - Let\'s Encrypt Auto Renew', h1: 'Cron SSL Certificate Renewal', description: 'Automate SSL certificate renewal with cron and Let\'s Encrypt. Monthly schedule for certbot auto-renewal.', explanation: 'Let\'s Encrypt certificates expire every 90 days. Use 0 0 1 * * to attempt renewal monthly. Certbot handles the actual renewal logic and only renews when needed.', faq: [{ q: 'How do I auto-renew Let\'s Encrypt with cron?', a: 'Add: 0 0 1 * * certbot renew --quiet && systemctl reload nginx. Certbot only renews certificates that are near expiry.' }], keywords: ['cron ssl renewal', 'cron certbot', 'cron letsencrypt'] },
  { slug: 'cron-temp-cleanup', cron: '0 3 * * *', title: 'Cron Temp File Cleanup - Delete Old Temp Files', h1: 'Cron Temp File Cleanup', description: 'Clean up temporary files with cron. Run 0 3 * * * to delete old temp files at 3 AM daily.', explanation: 'Use 0 3 * * * to clean temp files at 3 AM daily. Example: find /tmp -type f -mtime +7 -delete removes files older than 7 days.', faq: [{ q: 'How do I auto-delete old temp files?', a: 'Use: 0 3 * * * find /tmp -type f -mtime +7 -delete to remove files older than 7 days.' }], keywords: ['cron temp cleanup', 'cron delete old files', 'cron clean tmp'] },
  { slug: 'cron-report-generation', cron: '0 8 * * 1-5', title: 'Cron Report Generation - Weekday Morning Reports', h1: 'Cron Report Generation', description: 'Generate reports automatically with cron. Run 0 8 * * 1-5 to produce reports at 8 AM on weekdays.', explanation: 'Use 0 8 * * 1-5 to generate reports at 8 AM Monday through Friday. Useful for daily sales reports, analytics summaries, and status dashboards.', faq: [{ q: 'How do I schedule report generation with cron?', a: 'Use 0 8 * * 1-5 for weekday morning reports. Adjust time and days as needed.' }], keywords: ['cron report generation', 'cron daily report', 'cron weekly report'] },
  { slug: 'cron-data-sync', cron: '*/15 * * * *', title: 'Cron Data Synchronization - Sync Every 15 Minutes', h1: 'Cron Data Sync Schedule', description: 'Automate data synchronization with cron. Run */15 * * * * to sync data every 15 minutes.', explanation: 'Use */15 * * * * to run data sync operations every 15 minutes. This is a good balance between data freshness and system load.', faq: [{ q: 'How do I set up data sync with cron?', a: 'Use */15 * * * * rsync -avz /source/ user@remote:/dest/ for file sync, or */15 * * * * your-sync-script.sh' }], keywords: ['cron data sync', 'cron rsync', 'cron file sync'] },
  { slug: 'cron-email-sending', cron: '0 9 * * 1', title: 'Cron Email Sending - Weekly Email at 9 AM Monday', h1: 'Cron Email Schedule', description: 'Schedule automated emails with cron. Run 0 9 * * 1 to send emails at 9 AM every Monday.', explanation: 'Use 0 9 * * 1 to trigger email sends at 9 AM every Monday. Useful for weekly newsletters, reminders, and summary emails.', faq: [{ q: 'How do I schedule emails with cron?', a: 'Use 0 9 * * 1 /path/to/send-email.sh for weekly Monday emails at 9 AM.' }], keywords: ['cron email', 'cron send email', 'cron newsletter'] },

  // === Platform-specific ===
  { slug: 'aws-eventbridge-cron', cron: 'cron(* * * * *)', title: 'AWS EventBridge Cron Expressions - Complete Guide', h1: 'AWS EventBridge Cron Expressions', description: 'Learn AWS EventBridge cron syntax. Different from Unix cron: uses cron() or rate() format with 6 fields.', explanation: 'AWS EventBridge uses a different cron format: cron(Minutes Hours Day-of-month Month Day-of-week Year). It requires a 6th field for year and uses ? for "any" in day fields. Example: cron(0 9 ? * MON-FRI *) for weekdays at 9 AM.', faq: [{ q: 'How does AWS EventBridge cron differ from Unix cron?', a: 'AWS uses 6 fields (adds Year), requires ? instead of * in day fields when the other day field is specified, and wraps expressions in cron() or rate().' }, { q: 'How do I run every 5 minutes in AWS EventBridge?', a: 'Use rate(5 minutes) or cron(0/5 * ? * * *). The rate() syntax is simpler for fixed intervals.' }], keywords: ['aws eventbridge cron', 'aws cron expression', 'aws lambda schedule'] },
  { slug: 'quartz-cron', cron: '0 * * ? * *', title: 'Quartz Cron Expressions - 7 Field Syntax', h1: 'Quartz Cron Expressions', description: 'Learn Quartz Scheduler cron syntax. 7-field format with seconds. Used in Java, Spring, and many enterprise schedulers.', explanation: 'Quartz cron uses 7 fields: Seconds Minutes Hours Day-of-month Month Day-of-week Year. Key differences: starts with seconds, supports L (last) and W (weekday) modifiers, uses ? for "no specific value".', faq: [{ q: 'How does Quartz cron differ from Unix cron?', a: 'Quartz has 7 fields (adds seconds at the start and year at the end), supports L/W modifiers, and uses ? instead of * in conflicting day fields.' }, { q: 'How do I run every 5 minutes in Quartz?', a: 'Use 0 */5 * * * ? in Quartz. The first field is seconds (0), then */5 in minutes, and ? in day-of-week.' }], keywords: ['quartz cron', 'quartz scheduler cron', 'java cron expression'] },
  { slug: 'kubernetes-cronjob', cron: '0 * * * *', title: 'Kubernetes CronJob Schedule - K8s Cron Expressions', h1: 'Kubernetes CronJob Schedule', description: 'Create Kubernetes CronJobs with cron expressions. Schedule containers to run on a time-based schedule.', explanation: 'Kubernetes CronJobs use standard Unix cron format in the schedule field. Example: schedule: "0 * * * *" creates a job that runs every hour. K8s adds features like concurrencyPolicy, startingDeadlineSeconds, and successfulJobsHistoryLimit.', faq: [{ q: 'How do I create a CronJob in Kubernetes?', a: 'Define a CronJob resource with a schedule field using cron syntax. Example: schedule: "0 2 * * *" runs daily at 2 AM.' }, { q: 'What happens if a CronJob runs too long?', a: 'Set activeDeadlineSeconds to limit run time. Use concurrencyPolicy: Forbid to prevent overlapping runs.' }], keywords: ['kubernetes cronjob', 'k8s cronjob', 'kubernetes cron schedule'] },
  { slug: 'github-actions-schedule', cron: '0 * * * *', title: 'GitHub Actions Schedule - Cron Syntax for Workflows', h1: 'GitHub Actions Schedule', description: 'Schedule GitHub Actions workflows with cron. Use the schedule trigger with cron expressions for automated CI/CD.', explanation: 'GitHub Actions uses standard cron in the schedule trigger: on: schedule: - cron: "0 * * * *". GitHub runs workflows at minimum 5-minute intervals. The shortest interval is every 5 minutes.', faq: [{ q: 'How do I schedule a GitHub Actions workflow?', a: 'Add on: schedule: - cron: "0 2 * * *" to your workflow YAML. This runs daily at 2:00 UTC.' }, { q: 'What is the minimum cron interval in GitHub Actions?', a: 'GitHub Actions has a minimum interval of 5 minutes. Scheduled workflows may be delayed during high load periods.' }], keywords: ['github actions schedule', 'github actions cron', 'github workflow cron'] },

  // === Business patterns ===
  { slug: 'cron-business-hours', cron: '0 9-17 * * 1-5', title: 'Cron During Business Hours - 9 AM to 5 PM Weekdays', h1: 'Cron During Business Hours', description: 'Run cron only during business hours (9 AM-5 PM, Mon-Fri) with 0 9-17 * * 1-5.', explanation: 'The expression 0 9-17 * * 1-5 combines a range (9-17) in the hour field with a range (1-5) in the day-of-week field. It triggers at the top of each hour from 9 AM to 5 PM, Monday through Friday.', faq: [{ q: 'How do I run a cron only during business hours?', a: 'Use 0 9-17 * * 1-5 in your crontab. This runs at 9, 10, 11, 12, 13, 14, 15, 16, and 17 (9 AM - 5 PM) on weekdays.' }, { q: 'Can I run every 30 minutes during business hours?', a: 'Yes. Use */30 9-17 * * 1-5 to run every 30 minutes from 9 AM to 5 PM on weekdays.' }], keywords: ['cron business hours', 'cron 9 to 5', 'cron work hours'] },
  { slug: 'cron-off-peak', cron: '0 0-5 * * *', title: 'Cron Off-Peak Hours - Midnight to 5 AM', h1: 'Cron Off-Peak Hours', description: 'Run cron during off-peak hours (midnight to 5 AM) with 0 0-5 * * *.', explanation: 'The expression 0 0-5 * * * runs at the top of each hour from midnight to 5 AM. Ideal for maintenance tasks that should not impact user traffic.', faq: [{ q: 'How do I schedule tasks during off-peak hours?', a: 'Use 0 0-5 * * * for midnight to 5 AM. Adjust the range for your off-peak window.' }], keywords: ['cron off peak', 'cron maintenance window', 'cron night time'] },
  { slug: 'cron-lunch-time', cron: '0 12 * * 1-5', title: 'Cron at Lunch Time - Weekdays at Noon', h1: 'Cron at Lunch Time', description: 'Run a cron job at lunch time (noon on weekdays) with 0 12 * * 1-5.', explanation: 'The expression 0 12 * * 1-5 runs at noon Monday through Friday. Useful for midday maintenance or notifications.', faq: [{ q: 'How do I run a cron at lunch time on weekdays?', a: 'Use 0 12 * * 1-5 in your crontab for noon on weekdays.' }], keywords: ['cron lunch time', 'cron noon weekdays'] },
  { slug: 'cron-every-5-minutes-weekdays', cron: '*/5 * * * 1-5', title: 'Cron Every 5 Minutes on Weekdays Only', h1: 'Cron Every 5 Minutes on Weekdays', description: 'Run a cron every 5 minutes but only on weekdays with */5 * * * 1-5.', explanation: 'The expression */5 * * * 1-5 combines a step (*/5) in the minute field with a range (1-5) in the day-of-week field.', faq: [{ q: 'How do I run every 5 minutes on weekdays only?', a: 'Use */5 * * * 1-5 in your crontab.' }], keywords: ['cron every 5 minutes weekdays', '*/5 * * * 1-5'] },
  { slug: 'cron-every-15-minutes-business-hours', cron: '*/15 9-17 * * 1-5', title: 'Cron Every 15 Minutes During Business Hours', h1: 'Cron Every 15 Min (Business Hours)', description: 'Run a cron every 15 minutes from 9 AM to 5 PM on weekdays with */15 9-17 * * 1-5.', explanation: 'The expression */15 9-17 * * 1-5 triggers at 0, 15, 30, 45 minutes past each hour from 9 AM to 5 PM, Monday through Friday.', faq: [{ q: 'How do I run every 15 minutes during 9-to-5?', a: 'Use */15 9-17 * * 1-5 in your crontab.' }], keywords: ['cron 15 min business hours', '*/15 9-17 * * 1-5'] },
  { slug: 'cron-every-hour-at-half-past', cron: '30 * * * *', title: 'Cron Every Hour at Half Past', h1: 'Cron Every Hour at :30', description: 'Run a cron every hour at half past (:30) with 30 * * * *.', explanation: 'The expression 30 * * * * runs at :30 past every hour (00:30, 01:30, 02:30, etc.).', faq: [{ q: 'How do I run a cron at :30 every hour?', a: 'Use 30 * * * * in your crontab.' }], keywords: ['cron half past', 'cron :30', '30 * * * *'] },
  { slug: 'cron-midnight-weekdays', cron: '0 0 * * 1-5', title: 'Cron Midnight on Weekdays Only', h1: 'Cron Midnight on Weekdays', description: 'Run a cron at midnight but only on weekdays with 0 0 * * 1-5.', explanation: 'The expression 0 0 * * 1-5 runs at midnight Monday through Friday. Skips weekends.', faq: [{ q: 'How do I run a cron at midnight on weekdays only?', a: 'Use 0 0 * * 1-5 in your crontab.' }], keywords: ['cron midnight weekdays', '0 0 * * 1-5'] },

  // === More weekday/time combos ===
  { slug: 'weekdays-10am', cron: '0 10 * * 1-5', title: 'Cron Weekdays at 10 AM', h1: 'Cron Weekdays at 10 AM', description: 'Run a cron job weekdays at 10 AM with 0 10 * * 1-5.', explanation: 'The expression 0 10 * * 1-5 runs at 10:00 AM Monday through Friday.', faq: [{ q: 'What cron runs at 10 AM on weekdays?', a: 'Use 0 10 * * 1-5 in your crontab.' }], keywords: ['cron weekdays 10am', '0 10 * * 1-5'] },
  { slug: 'weekdays-3pm', cron: '0 15 * * 1-5', title: 'Cron Weekdays at 3 PM', h1: 'Cron Weekdays at 3 PM', description: 'Run a cron job weekdays at 3 PM with 0 15 * * 1-5.', explanation: 'The expression 0 15 * * 1-5 runs at 3:00 PM Monday through Friday.', faq: [{ q: 'How do I run a cron at 3 PM on weekdays?', a: 'Use 0 15 * * 1-5 in your crontab.' }], keywords: ['cron weekdays 3pm', '0 15 * * 1-5'] },
  { slug: 'weekends-noon', cron: '0 12 * * 0,6', title: 'Cron Weekends at Noon', h1: 'Cron Weekends at Noon', description: 'Run a cron job on weekends at noon with 0 12 * * 0,6.', explanation: 'The expression 0 12 * * 0,6 runs at noon on Saturday and Sunday.', faq: [{ q: 'How do I run a cron at noon on weekends?', a: 'Use 0 12 * * 0,6 in your crontab.' }], keywords: ['cron weekends noon', '0 12 * * 0,6'] },
  { slug: 'weekends-5pm', cron: '0 17 * * 0,6', title: 'Cron Weekends at 5 PM', h1: 'Cron Weekends at 5 PM', description: 'Run a cron job on weekends at 5 PM with 0 17 * * 0,6.', explanation: 'The expression 0 17 * * 0,6 runs at 5:00 PM on Saturday and Sunday.', faq: [{ q: 'What cron runs at 5 PM on weekends?', a: 'Use 0 17 * * 0,6 in your crontab.' }], keywords: ['cron weekends 5pm', '0 17 * * 0,6'] },

  // === Monthly specific dates ===
  { slug: 'every-monday-friday', cron: '0 0 * * 1,5', title: 'Cron Monday and Friday', h1: 'Cron Monday and Friday', description: 'Run a cron on Monday and Friday with 0 0 * * 1,5.', explanation: 'The expression 0 0 * * 1,5 uses comma-separated values: Monday(1) and Friday(5).', faq: [{ q: 'How do I run a cron on Monday and Friday?', a: 'Use 0 0 * * 1,5 in your crontab.' }], keywords: ['cron monday friday', '0 0 * * 1,5'] },
  { slug: 'every-5th-of-month', cron: '0 0 5 * *', title: 'Cron Every 5th of the Month', h1: 'Cron Every 5th of the Month', description: 'Run a cron on the 5th of every month with 0 0 5 * *.', explanation: 'The expression 0 0 5 * * runs at midnight on the 5th day of every month.', faq: [{ q: 'What cron runs on the 5th of every month?', a: 'Use 0 0 5 * * in your crontab.' }], keywords: ['cron 5th of month', '0 0 5 * *'] },
  { slug: 'every-10th-of-month', cron: '0 0 10 * *', title: 'Cron Every 10th of the Month', h1: 'Cron Every 10th of the Month', description: 'Run a cron on the 10th of every month with 0 0 10 * *.', explanation: 'The expression 0 0 10 * * runs at midnight on the 10th day of every month.', faq: [{ q: 'How do I run a cron on the 10th of each month?', a: 'Use 0 0 10 * * in your crontab.' }], keywords: ['cron 10th of month', '0 0 10 * *'] },
  { slug: 'every-20th-of-month', cron: '0 0 20 * *', title: 'Cron Every 20th of the Month', h1: 'Cron Every 20th of the Month', description: 'Run a cron on the 20th of every month with 0 0 20 * *.', explanation: 'The expression 0 0 20 * * runs at midnight on the 20th day of every month.', faq: [{ q: 'What cron runs on the 20th of every month?', a: 'Use 0 0 20 * * in your crontab.' }], keywords: ['cron 20th of month', '0 0 20 * *'] },
  { slug: 'twice-monthly-1st-15th', cron: '0 0 1,15 * *', title: 'Cron Twice Monthly (1st and 15th)', h1: 'Cron Twice Monthly', description: 'Run a cron on the 1st and 15th of every month with 0 0 1,15 * *.', explanation: 'The expression 0 0 1,15 * * runs at midnight on the 1st and 15th of every month. Common for payroll and billing cycles.', faq: [{ q: 'How do I run a cron twice a month?', a: 'Use 0 0 1,15 * * in your crontab for the 1st and 15th of each month.' }], keywords: ['cron twice monthly', '0 0 1,15 * *', 'cron semimonthly'] },
  { slug: 'cron-every-january-1st', cron: '0 0 1 1 *', title: 'Cron Every January 1st - New Year Schedule', h1: 'Cron Every January 1st', description: 'Run a cron on January 1st every year with 0 0 1 1 *.', explanation: 'The expression 0 0 1 1 * runs at midnight on January 1st every year. The month field is set to 1 (January).', faq: [{ q: 'How do I run a cron on New Year\'s Day?', a: 'Use 0 0 1 1 * in your crontab for January 1st at midnight.' }], keywords: ['cron january 1st', 'cron new year', '0 0 1 1 *'] },

  // === Hourly with minute offsets ===
  { slug: 'every-2-hours-at-15', cron: '15 */2 * * *', title: 'Cron Every 2 Hours at :15', h1: 'Cron Every 2 Hours at :15', description: 'Run a cron every 2 hours at minute 15 with 15 */2 * * *.', explanation: 'The expression 15 */2 * * * runs at :15 past every 2nd hour: 00:15, 02:15, 04:15, 06:15, etc.', faq: [{ q: 'How do I run every 2 hours at :15?', a: 'Use 15 */2 * * * in your crontab.' }], keywords: ['cron every 2 hours :15', '15 */2 * * *'] },
  { slug: 'every-4-hours-at-30', cron: '30 */4 * * *', title: 'Cron Every 4 Hours at :30', h1: 'Cron Every 4 Hours at :30', description: 'Run a cron every 4 hours at minute 30 with 30 */4 * * *.', explanation: 'The expression 30 */4 * * * runs at :30 past every 4th hour: 00:30, 04:30, 08:30, 12:30, 16:30, 20:30.', faq: [{ q: 'What cron runs every 4 hours at :30?', a: 'Use 30 */4 * * * in your crontab.' }], keywords: ['cron every 4 hours :30', '30 */4 * * *'] },
  { slug: 'every-6-hours-at-45', cron: '45 */6 * * *', title: 'Cron Every 6 Hours at :45', h1: 'Cron Every 6 Hours at :45', description: 'Run a cron every 6 hours at minute 45 with 45 */6 * * *.', explanation: 'The expression 45 */6 * * * runs at :45 past every 6th hour: 00:45, 06:45, 12:45, 18:45.', faq: [{ q: 'How do I run every 6 hours at :45?', a: 'Use 45 */6 * * * in your crontab.' }], keywords: ['cron every 6 hours :45', '45 */6 * * *'] },

  // === Specific time patterns ===
  { slug: 'cron-specific-time', cron: '30 14 * * *', title: 'Cron at Specific Time - How to Set Exact Time', h1: 'Cron at Specific Time (2:30 PM)', description: 'Set a cron job at a specific time. Example: 30 14 * * * runs at 2:30 PM daily. Learn the minute-hour format.', explanation: 'To set a specific time, use exact values in the minute and hour fields. 30 14 * * * means minute=30, hour=14 (2:30 PM). The remaining * fields mean every day.', faq: [{ q: 'How do I set a cron at a specific time?', a: 'Use exact minute and hour values. For 3:45 PM: 45 15 * * *. For 8:05 AM: 5 8 * * *.' }], keywords: ['cron specific time', 'cron exact time', 'cron set time'] },
  { slug: 'cron-twice-daily-8am-8pm', cron: '0 8,20 * * *', title: 'Cron Twice Daily at 8 AM and 8 PM', h1: 'Cron Twice Daily (8 AM & 8 PM)', description: 'Run a cron twice daily at 8 AM and 8 PM with 0 8,20 * * *.', explanation: 'The expression 0 8,20 * * * runs at 8:00 AM and 8:00 PM every day.', faq: [{ q: 'How do I run a cron at 8 AM and 8 PM?', a: 'Use 0 8,20 * * * in your crontab.' }], keywords: ['cron twice daily 8am 8pm', '0 8,20 * * *'] },
  { slug: 'cron-every-30-minutes-8am-5pm', cron: '*/30 8-17 * * *', title: 'Cron Every 30 Min from 8 AM to 5 PM', h1: 'Cron Every 30 Min (8 AM - 5 PM)', description: 'Run a cron every 30 minutes from 8 AM to 5 PM with */30 8-17 * * *.', explanation: 'The expression */30 8-17 * * * runs at :00 and :30 past each hour from 8 AM to 5 PM every day.', faq: [{ q: 'How do I run every 30 minutes during work hours?', a: 'Use */30 8-17 * * * in your crontab.' }], keywords: ['cron every 30 min work hours', '*/30 8-17 * * *'] },
  { slug: 'cron-sunday-midnight', cron: '0 0 * * 0', title: 'Cron Every Sunday at Midnight', h1: 'Cron Every Sunday at Midnight', description: 'Run a cron every Sunday at midnight with 0 0 * * 0. Weekly Sunday maintenance.', explanation: 'The expression 0 0 * * 0 runs at midnight every Sunday. Useful for weekly maintenance tasks.', faq: [{ q: 'How do I run a cron every Sunday at midnight?', a: 'Use 0 0 * * 0 in your crontab.' }], keywords: ['cron sunday midnight', '0 0 * * 0'] },
  { slug: 'cron-saturday-midnight', cron: '0 0 * * 6', title: 'Cron Every Saturday at Midnight', h1: 'Cron Every Saturday at Midnight', description: 'Run a cron every Saturday at midnight with 0 0 * * 6.', explanation: 'The expression 0 0 * * 6 runs at midnight every Saturday.', faq: [{ q: 'What cron runs every Saturday at midnight?', a: 'Use 0 0 * * 6 in your crontab.' }], keywords: ['cron saturday midnight', '0 0 * * 6'] },

  // === Cron how-to guides ===
  { slug: 'how-to-edit-crontab', cron: '0 0 * * *', title: 'How to Edit Crontab - crontab -e Guide', h1: 'How to Edit Crontab', description: 'Learn how to edit your crontab with crontab -e. Add, modify, and remove cron jobs step by step.', explanation: 'Use crontab -e to open your crontab in the default editor. Each line is one cron job in the format: minute hour day month weekday command. Save and exit to activate.', faq: [{ q: 'How do I edit my crontab?', a: 'Run crontab -e in your terminal. This opens your crontab file in an editor (usually vi or nano). Add lines in cron format, save, and exit.' }, { q: 'How do I list my current cron jobs?', a: 'Run crontab -l to list all cron jobs for the current user.' }], keywords: ['how to edit crontab', 'crontab -e', 'how to add cron job'] },
  { slug: 'cron-environment-variables', cron: '0 0 * * *', title: 'Cron Environment Variables - PATH, SHELL, MAILTO', h1: 'Cron Environment Variables', description: 'Understand cron environment variables. Set PATH, SHELL, MAILTO in your crontab for proper execution.', explanation: 'Cron runs with a minimal environment. Set PATH at the top of your crontab if commands are not found. Use MAILTO to redirect output emails. Use SHELL to change the shell.', faq: [{ q: 'Why does my cron job work manually but fails in crontab?', a: 'Cron uses a minimal PATH. Add PATH=/usr/local/bin:/usr/bin:/bin at the top of your crontab, or use full paths to all commands.' }, { q: 'How do I stop cron from sending emails?', a: 'Add MAILTO="" at the top of your crontab, or redirect output: command >/dev/null 2>&1' }], keywords: ['cron environment variables', 'cron PATH', 'cron MAILTO'] },
  { slug: 'cron-troubleshooting', cron: '0 0 * * *', title: 'Cron Job Not Running - Troubleshooting Guide', h1: 'Cron Troubleshooting Guide', description: 'Fix cron jobs that are not running. Common causes: PATH issues, permissions, environment, and syntax errors.', explanation: 'Common reasons cron jobs fail: (1) Minimal PATH environment - use full paths, (2) No terminal/shell features, (3) Percent signs must be escaped in crontab, (4) Script must be executable, (5) Check /var/log/cron or journalctl for errors.', faq: [{ q: 'Why is my cron job not running?', a: 'Check: (1) Is the script executable? chmod +x script.sh, (2) Are you using full paths?, (3) Check logs: grep CRON /var/log/syslog, (4) Is the syntax correct? Run crontab -l to verify.' }, { q: 'How do I debug a cron job?', a: 'Redirect output to a log file: * * * * * /path/to/command >> /tmp/cron.log 2>&1. Then check the log for errors.' }], keywords: ['cron not running', 'cron troubleshooting', 'cron job fails'] },
  { slug: 'cron-timezone', cron: '0 0 * * *', title: 'Cron Timezone - Which TZ Does Cron Use?', h1: 'Cron Timezone Settings', description: 'Understand which timezone cron uses and how to change it. Set TZ variable or use CRON_TZ in your crontab.', explanation: 'Cron uses the system timezone by default. You can set CRON_TZ=America/New_York at the top of your crontab, or set TZ per job: CRON_TZ=UTC before the job line.', faq: [{ q: 'What timezone does cron use?', a: 'Cron uses the system timezone. Check with timedatectl on systemd systems. Set CRON_TZ in your crontab to override.' }, { q: 'How do I run a cron in UTC?', a: 'Add CRON_TZ=UTC at the top of your crontab, or prefix specific jobs: 0 0 * * * TZ=UTC command' }], keywords: ['cron timezone', 'cron TZ', 'CRON_TZ'] },

  // === Every Nth month ===
  { slug: 'every-february', cron: '0 0 1 2 *', title: 'Cron Every February - Annual February Schedule', h1: 'Cron Every February', description: 'Run a cron job every February 1st with 0 0 1 2 *.', explanation: 'The expression 0 0 1 2 * runs at midnight on February 1st every year. The month field is 2 (February).', faq: [{ q: 'How do I run a cron every February?', a: 'Use 0 0 1 2 * for February 1st at midnight. Change the day-of-month for other February dates.' }], keywords: ['cron february', '0 0 1 2 *'] },
  { slug: 'every-july', cron: '0 0 1 7 *', title: 'Cron Every July - Annual July Schedule', h1: 'Cron Every July', description: 'Run a cron job every July 1st with 0 0 1 7 *.', explanation: 'The expression 0 0 1 7 * runs at midnight on July 1st every year.', faq: [{ q: 'What cron runs every July?', a: 'Use 0 0 1 7 * in your crontab for July 1st at midnight.' }], keywords: ['cron july', '0 0 1 7 *'] },
  { slug: 'every-december', cron: '0 0 1 12 *', title: 'Cron Every December - Annual December Schedule', h1: 'Cron Every December', description: 'Run a cron job every December 1st with 0 0 1 12 *.', explanation: 'The expression 0 0 1 12 * runs at midnight on December 1st every year.', faq: [{ q: 'How do I run a cron every December?', a: 'Use 0 0 1 12 * in your crontab for December 1st at midnight.' }], keywords: ['cron december', '0 0 1 12 *'] },
  { slug: 'every-october', cron: '0 0 1 10 *', title: 'Cron Every October - Annual October Schedule', h1: 'Cron Every October', description: 'Run a cron job every October 1st with 0 0 1 10 *.', explanation: 'The expression 0 0 1 10 * runs at midnight on October 1st every year.', faq: [{ q: 'What cron runs every October?', a: 'Use 0 0 1 10 * in your crontab.' }], keywords: ['cron october', '0 0 1 10 *'] },
  { slug: 'every-april', cron: '0 0 1 4 *', title: 'Cron Every April - Annual April Schedule', h1: 'Cron Every April', description: 'Run a cron job every April 1st with 0 0 1 4 *.', explanation: 'The expression 0 0 1 4 * runs at midnight on April 1st every year.', faq: [{ q: 'How do I run a cron every April?', a: 'Use 0 0 1 4 * in your crontab for April 1st at midnight.' }], keywords: ['cron april', '0 0 1 4 *'] },
  { slug: 'every-monday-wednesday', cron: '0 0 * * 1,3', title: 'Cron Monday and Wednesday', h1: 'Cron Monday and Wednesday', description: 'Run a cron on Monday and Wednesday with 0 0 * * 1,3.', explanation: 'The expression 0 0 * * 1,3 uses comma-separated values for Monday(1) and Wednesday(3).', faq: [{ q: 'How do I run a cron on Monday and Wednesday?', a: 'Use 0 0 * * 1,3 in your crontab.' }], keywords: ['cron monday wednesday', '0 0 * * 1,3'] },
  { slug: 'cron-every-minute-for-one-hour', cron: '* 9 * * *', title: 'Cron Every Minute During 9 AM Hour', h1: 'Cron Every Minute (9 AM Hour Only)', description: 'Run a cron every minute but only during the 9 AM hour with * 9 * * *.', explanation: 'The expression * 9 * * * runs every minute from 9:00 to 9:59 AM. The minute field is wildcard (*) and the hour field is fixed at 9.', faq: [{ q: 'How do I run every minute for one specific hour?', a: 'Set the hour field to the desired hour and leave minute as *. Example: * 14 * * * runs every minute from 2:00 to 2:59 PM.' }], keywords: ['cron every minute one hour', '* 9 * * *'] },
  { slug: 'cron-every-other-hour', cron: '0 */2 * * *', title: 'Cron Every Other Hour - Alternating Hours', h1: 'Cron Every Other Hour', description: 'Run a cron every other hour (every 2 hours) with 0 */2 * * *.', explanation: 'The expression 0 */2 * * * runs at the top of every 2nd hour: 0:00, 2:00, 4:00, 6:00, 8:00, 10:00, 12:00, 14:00, 16:00, 18:00, 20:00, 22:00.', faq: [{ q: 'How do I run a cron every other hour?', a: 'Use 0 */2 * * * in your crontab. This runs at midnight, 2 AM, 4 AM, etc.' }], keywords: ['cron every other hour', 'cron alternating hours', '0 */2 * * *'] },

  // === Extra high-value SEO patterns ===
  { slug: 'cron-every-week', cron: '0 0 * * 0', title: 'Cron Every Week - Weekly Schedule', h1: 'Cron Every Week', description: 'Run a cron job every week with 0 0 * * 0. Weekly schedule at midnight Sunday.', explanation: 'The expression 0 0 * * 0 runs at midnight every Sunday. This is the standard weekly schedule. Change the day-of-week for other days.', faq: [{ q: 'How do I run a cron every week?', a: 'Use 0 0 * * 0 for weekly on Sunday at midnight. Change to 0 0 * * 1 for Monday, etc.' }], keywords: ['cron every week', 'weekly cron', 'cron weekly schedule'] },
  { slug: 'cron-every-sunday-8am', cron: '0 8 * * 0', title: 'Cron Every Sunday at 8 AM', h1: 'Cron Every Sunday at 8 AM', description: 'Run a cron every Sunday at 8 AM with 0 8 * * 0.', explanation: 'The expression 0 8 * * 0 runs at 8:00 AM every Sunday.', faq: [{ q: 'What cron runs every Sunday at 8 AM?', a: 'Use 0 8 * * 0 in your crontab.' }], keywords: ['cron sunday 8am', '0 8 * * 0'] },
  { slug: 'cron-5-minutes-after-midnight', cron: '5 0 * * *', title: 'Cron 5 Minutes After Midnight Daily', h1: 'Cron at 12:05 AM Daily', description: 'Run a cron 5 minutes after midnight every day with 5 0 * * *.', explanation: 'The expression 5 0 * * * runs at 00:05 (5 minutes after midnight) every day. Useful when you want to avoid the exact midnight rush.', faq: [{ q: 'How do I run a cron 5 minutes after midnight?', a: 'Use 5 0 * * * in your crontab. This avoids the midnight spike when many cron jobs run simultaneously.' }], keywords: ['cron 5 minutes after midnight', '5 0 * * *', 'cron 12:05 am'] },
  { slug: 'cron-every-30-minutes-at-0-and-30', cron: '0,30 * * * *', title: 'Cron Every 30 Minutes at :00 and :30', h1: 'Cron Every 30 Minutes (:00 and :30)', description: 'Run a cron every 30 minutes at :00 and :30 with 0,30 * * * *.', explanation: 'The expression 0,30 * * * * is equivalent to */30 * * * *. It explicitly lists the minutes: 0 and 30 of every hour.', faq: [{ q: 'What is the difference between */30 and 0,30?', a: 'They produce the same result for 30-minute intervals. */30 uses the step operator, 0,30 uses explicit values. Both run at :00 and :30.' }], keywords: ['cron 0,30', '0,30 * * * *', 'cron every 30 at 0 30'] },
]
